apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://github.com/Utwo/k8s-playground
      path: monitoring/grafana
      targetRevision: HEAD
      ref: myRepo # repo is available via symlink "myRepo"
      directory:
        recurse: true
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 8.8.4
      chart: grafana
      helm:
        valueFiles:
          - $myRepo/monitoring/grafana/helm-chart-values/values.yaml
  destination:
    namespace: grafana
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
