apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://github.com/Utwo/k8s-playground
      path: monitoring/kube-prometheus-stack
      targetRevision: HEAD
      ref: myRepo # repo is available via symlink "myRepo"
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 69.4.0
      chart: kube-prometheus-stack
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - $myRepo/monitoring/kube-prometheus-stack/helm-chart-values/values.yaml
  destination:
    name: in-cluster
    namespace: kube-prometheus-stack
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
