apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://github.com/Utwo/k8s-playground
      path: monitoring/loki
      targetRevision: HEAD
      ref: myRepo # repo is available via symlink "myRepo"
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 6.25.0
      chart: loki
      helm:
        valueFiles:
          - $myRepo/monitoring/loki/helm-chart-values/values.yaml
  destination:
    namespace: loki
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
