apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://github.com/Utwo/k8s-playground
      path: monitoring/victoria-metrics
      targetRevision: HEAD
      ref: myRepo
      directory:
        recurse: true
    - repoURL: https://victoriametrics.github.io/helm-charts
      targetRevision: 0.40.4
      chart: victoria-metrics-operator
      helm:
        valuesObject:
          fullnameOverride: vm-operator
          logLevel: error
          env:
            - name: VM_ENABLEDPROMETHEUSCONVERTER_PODMONITOR
              value: "false"
            - name: VM_ENABLEDPROMETHEUSCONVERTER_SERVICESCRAPE
              value: "false"
            - name: VM_ENABLEDPROMETHEUSCONVERTER_PROMETHEUSRULE
              value: "true"
            - name: VM_ENABLEDPROMETHEUSCONVERTER_PROBE
              value: "false"
            - name: VM_ENABLEDPROMETHEUSCONVERTER_SCRAPECONFIG
              value: "false"
          admissionWebhooks:
            certManager:
              enabled: true
          operator:
            enable_converter_ownership: true
  destination:
    namespace: victoria-metrics
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
