apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: victoria-metrics
  namespace: argocd
spec:
  project: monitoring
  sources:
    - repoURL: https://github.com/Utwo/k8s-playground
      path: monitoring/victoria-metrics
      targetRevision: HEAD
      ref: myRepo
    - repoURL: https://victoriametrics.github.io/helm-charts
      targetRevision: 0.13.5
      chart: victoria-metrics-single
      helm:
        valueFiles:
          - $myRepo/monitoring/victoria-metrics/helm-chart-values/vm-single-values.yaml
    - repoURL: https://victoriametrics.github.io/helm-charts
      targetRevision: 0.40.4
      chart: victoria-metrics-operator
      helm:
        parameters:
          - name: fullnameOverride
            value: vm-operator
          # - name: admissionWebhooks.certManager.enabled
          #   value: "true"
          - name: "logLevel"
            value: "error"
          - name: "operator.enable_converter_ownership"
            value: "true"
          - name: "watchNamespaces[0]"
            value: "victoria-metrics"
          - name: "watchNamespaces[1]"
            value: "kube-prometheus-extra"
  destination:
    namespace: victoria-metrics
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
