apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: victoria-metrics-auth
spec:
    secretTemplates:
        - name: victoria-metrics-auth
          stringData:
            AUTH_TOKEN_METRICS: ENC[AES256_GCM,data:dmRzP7dCV9JPRQF/,iv:QLkW3Y+huFk/Pp1Qa87q4D8C/vK5AzWsrqvgTQVNi4g=,tag:S4RpEbWsDEcXmJiadMHcwg==,type:str]
            AUTH_TOKEN_LOGS: ENC[AES256_GCM,data:q4qZFz4V81T2JUl9,iv:+0Ta9wDVV+FoFyJXkTvPe/IOPMVAjjX54R7/woceLqw=,tag:HKb4MCJrGFMiwc2B3W5vcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eUdkdHhYbm1OM2k4aXZ6
            YXhIZDUydGNqQm1vclZtWmJlR3g0aHdaaHpvClZudlRvVTc4VlVVbmJManFFRWdz
            TlJ1ZDFWNkFQZ2RYOHBmNFRRUFRsT3cKLS0tIDg0cG1PNzd1ZTNJSnpEcTJZT2V0
            VXN3bWpuTVMxSTJ2NGxyUTV2dW92RkkK97YKXUODCEgs55w1TWogEiDwnzzsQb1I
            jCD2WfiyMXsQMwmvtJfeejzw9qlyku29l6aGSJZKR0PGBzdzgP1gZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-16T15:31:59Z"
    mac: ENC[AES256_GCM,data:UrjceBKdOh8lOpncRre192tx2dvKFhGTjQxFk2w+xrSOHHxXB6N7lGBJVG98e0/YkwMXNJvfpq6G/2ZYhg5YmT67O4+ZcBqkrU5Far+3vTgx3al+EBEFiAwi7TZ4/jP1io4mZi08kmHtyL1+RvuDAH+Ld/RMmfOm0/9uv70378U=,iv:WLf8kvXTb0HRj0brXeVsKX7QOTztH9s+kVPn7tFbcbg=,tag:OzkMjlVGbrkoEcsYU3TiWA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
