apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vm-user-logs
spec:
  targetRefs:
    - static:
        url: http://vlogs-vm-logs:9428
  tokenRef:
    name: victoria-metrics-auth
    key: AUTH_TOKEN_LOGS
