apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: sandbox-apps
servers: 1
agents: 1
network: k8s-sandbox
token: superSecretToken
ports:
  - port: 8000:80
    nodeFilters:
      - loadbalancer
  - port: 4430:443
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
    nodeLabels:
      - label: node=default
        nodeFilters:
          - server:0
