configmap:
  # -- If enabled, promtail config will be created as a ConfigMap instead of a secret
  enabled: true

config:
  snippets:
    pipelineStages:
      - cri: {}
      - match:
          selector: '{app="kubernetes-event-exporter"}'
          stages:
            - json:
                expressions:
                  namespace: metadata.namespace
            - labels:
                targetNamespace: namespace
      - drop:
          source: "component"
          value: "runner"
  logLevel: warn

  clients:
    - url: http://victorialogs.victoria-metrics.svc.cluster.local:9428/insert/loki/api/v1/push?_stream_fields=instance,job,host,app
      tenant_id: "my_org"
      # bearer_token: <secret>
      basic_auth:
        username: admin
        password: ${AUTH_TOKEN_LOGS}

extraEnv:
  - name: AUTH_TOKEN_LOGS
    valueFrom:
      secretKeyRef:
        name: promtail-secret
        key: AUTH_TOKEN_LOGS
