apiVersion: v1
kind: Service
metadata:
  name: backend-canary
  labels:
    app: backend
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: http
  selector:
    app: backend
    app.kubernetes.io/name: playground-sandbox
