backend:
  serviceMonitor:
    enabled: true
    additionalLabels:
      release: kube-prometheus-stack-k3d-apps
  env:
    - name: SANDBOX_NODE_LABEL
      value: "default"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://otel-collector.172.20.0.3.nip.io"
    - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
      valueFrom:
        secretKeyRef:
          name: playground-sandbox
          key: OTEL_EXPORTER_OTLP_TRACES_HEADERS

frontend:
  annotations:
    argocd.argoproj.io/sync-wave: "5"

ingress:
  className: nginx
