apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: playground-sandbox-pr
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          owner: utwo
          repo: playground-sandbox
          appSecretName: github-utwo-repo
          # Labels is used to filter the PRs that you want to target. (optional)
          labels:
            - preview
        requeueAfterSeconds: 30
  template:
    metadata:
      name: "playground-sandbox-pr-{{.branch_slug}}-{{.number}}"
      annotations:
        argocd.argoproj.io/default-view: pods
        notifications.argoproj.io/subscribe.on-deployed.github: "utwo/playground-sandbox"
    spec:
      project: apps
      sources:
        - repoURL: https://github.com/Utwo/k8s-playground
          path: apps/playground-sandbox
          targetRevision: HEAD
        - repoURL: https://github.com/Utwo/playground-sandbox
          path: helm/charts/playground-sandbox
          targetRevision: "{{.head_sha}}"
          helm:
            valuesObject:
              volumeClaimDefault:
                backend:
                  hostPath:
                    path: "/tmp/k3dvol/{{.branch_slug}}-{{.number}}"
              volumeClaimPublic:
                backend:
                  hostPath:
                    path: "/tmp/k3dvol/{{.branch_slug}}-{{.number}}"
              backend:
                env:
                  - name: SANDBOX_NODE_LABEL
                    value: "default"
                  - name: OTEL_EXPORTER_OTLP_ENDPOINT
                    value: "http://hotel-collector.172.20.0.3.nip.io/v1/traces"
                  - name: OTEL_EXPORTER_OTLP_TRACES_HEADERS
                    valueFrom:
                      secretKeyRef:
                        name: playground-sandbox
                        key: OTEL_EXPORTER_OTLP_TRACES_HEADERS
            parameters:
              - name: backend.image.tag
                value: "pr-{{.number}}-{{.head_sha}}"
              - name: frontend.image.tag
                value: "pr-{{.number}}-{{.head_sha}}"
              - name: sandboxNamespace
                value: "public-{{.branch_slug}}-{{.number}}"
              - name: ingress.className
                value: "nginx"
              - name: ingress.domain
                value: "{{.branch_slug}}-{{.number}}.127.0.0.1.nip.io"
      destination:
        name: k3d-apps
        namespace: playground-sandbox-{{.branch_slug}}-{{.number}}
      info:
        - name: Webapp URL
          value: >-
            "https://{{.branch_slug}}-{{.number}}.127.0.0.1.nip.io:8000"
        - name: API URL
          value: >-
            "https://api.{{.branch_slug}}-{{.number}}.127.0.0.1.nip.io:8000"
      syncPolicy:
        automated:
          prune: true
        syncOptions:
          - CreateNamespace=true
        managedNamespaceMetadata:
          labels:
            app.kubernetes.io/instance: playground-sandbox-pr-{{.branch_slug}}-{{.number}}
          annotations:
            argocd.argoproj.io/tracking-id: >-
              <argocd-application-name>:app/Namespace:<namespace>/<namespace>
