apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: playground-sandbox
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/Utwo/k8s-playground
        revision: HEAD
        directories:
          - path: apps/playground-sandbox/envs/*
  template:
    metadata:
      name: playground-sandbox-{{ .path.basename }}
      annotations:
        kargo.akuity.io/authorized-stage: kargo-project-playground-sandbox:{{ .path.basename }}
    spec:
      project: apps
      sources:
        - repoURL: https://github.com/Utwo/k8s-playground
          path: playground-sandbox
          targetRevision: stage/{{ .path.basename }}
          directory:
            recurse: true
        # - repoURL: https://github.com/Utwo/k8s-playground
        #   path: apps/playground-sandbox/envs/{{ .path.basename }}
        #   targetRevision: HEAD
        #   ref: values
        #   directory:
        #     recurse: true
        # - repoURL: https://github.com/Utwo/playground-sandbox
        #   path: ./helm/charts/playground-sandbox
        #   targetRevision: HEAD
        #   helm:
        #     valueFiles:
        #       - $values/apps/playground-sandbox/common/values.yaml
        #       - $values/apps/playground-sandbox/envs/{{ .path.basename }}/values.yaml
        #     parameters:
        #       - name: backend.image.tag
        #         value: $ARGOCD_APP_REVISION_SHORT
        #       - name: frontend.image.tag
        #         value: $ARGOCD_APP_REVISION_SHORT
      destination:
        name: k3d-apps
        namespace: playground-sandbox-{{ .path.basename }}
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
