apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-sandbox
  namespace: argocd
spec:
  project: apps
  sources:
    - repoURL: https://github.com/Utwo/playground-sandbox
      path: ./k8s/playground-sandbox
      targetRevision: HEAD
      helm:
        parameters:
          - name: backend.image.tag
            value: $ARGOCD_APP_REVISION_SHORT
          - name: frontend.image.tag
            value: $ARGOCD_APP_REVISION_SHORT
          - name: ingress.className
            value: "nginx"
  destination:
    name: k3d-apps
    namespace: playground-sandbox
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true
