apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-sandbox
  namespace: argocd
spec:
  project: apps
  sources:
    - repoURL: https://github.com/Utwo/sandbox-playground
      path: ./k8s/overlays/local
      targetRevision: HEAD
      kustomize:
        patches:
          - target:
              kind: RoleBinding
              name: modify-pods-to-sa
            patch: |-
              - op: replace
                path: /subjects/0/namespace
                value: playground-sandbox
          - patch: |-
              apiVersion: networking.k8s.io/v1
              kind: Ingress
              metadata:
                name: app-ingress
              spec:
                ingressClassName: nginx
  destination:
    name: k3d-apps
    namespace: playground-sandbox
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
