apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: promtail-secret
spec:
    secretTemplates:
        - name: promtail-secret
          stringData:
            LOKI_PASSWORD: ENC[AES256_GCM,data:HHCU2Is=,iv:kqQiWQLMpQI3pCEsqL3+799bMtIZHoZSESBL+C2fC84=,tag:FAG7dVGelbGC3g3nxKeJTA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eUdkdHhYbm1OM2k4aXZ6
            YXhIZDUydGNqQm1vclZtWmJlR3g0aHdaaHpvClZudlRvVTc4VlVVbmJManFFRWdz
            TlJ1ZDFWNkFQZ2RYOHBmNFRRUFRsT3cKLS0tIDg0cG1PNzd1ZTNJSnpEcTJZT2V0
            VXN3bWpuTVMxSTJ2NGxyUTV2dW92RkkK97YKXUODCEgs55w1TWogEiDwnzzsQb1I
            jCD2WfiyMXsQMwmvtJfeejzw9qlyku29l6aGSJZKR0PGBzdzgP1gZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-18T17:20:54Z"
    mac: ENC[AES256_GCM,data:TevhCQR2B7AekHREOgGRUbzjMN1wZngurXj4W8G8HkgTPx/+IHAHFUbtINX47uIyQQotMusyIaNq7x03ZaPqUum//Cxvqe2jhXenv9E69q2MKHDOmmmNbhbvrNon6CAnO9lm8M4LQzLrcJ/R/SBUeTcOhqaKHNqcF3bsBQd0Lp0=,iv:KMukmTz3IuBSA1Ccnu2JTtRMCb5CSfZI8WRDiikqPIc=,tag:+6ZhOh8GBXRfUQof7jR1zA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
