apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vm-auth
spec:
  ingress:
    class_name: nginx
    host: collector.k3d-sandbox-control-serverlb.orb.local
  userNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: victoria-metrics
