apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vm-auth
spec:
  ingress:
    class_name: nginx
    host: collector.172.20.0.6.nip.io
  userNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: victoria-metrics
