apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: alert-server
spec:
  replicaCount: 1
  extraArgs:
    remoteWrite.disablePathAppend: "true"
  datasource:
    url: "http://vmsingle-server:8429/"
  remoteWrite:
    url: "http://vmsingle-server:8429/api/v1/write"
  remoteRead:
    url: "http://vmsingle-server:8429"
  notifier:
    url: "http://alertmanager.alertmanager:9093"
  evaluationInterval: "30s"
  selectAllByDefault: true
