apiVersion: operator.victoriametrics.com/v1beta1
kind: VLogs
metadata:
  name: vm-logs
spec:
  removePvcAfterDelete: true
  retentionPeriod: 1d
  storage:
    resources:
      requests:
        storage: 1Gi
  resources: {}
