apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: server
spec:
  retentionPeriod: 1d
  extraArgs:
    opentsdbHTTPListenAddr: ":4242"
    loggerLevel: WARN
    opentelemetry.usePrometheusNaming: "true"
    vmalert.proxyURL: "http://vmalert-alert-server:8080"
  resources: {}
