admin:
  existingSecret: grafana-secret
envFromSecret: grafana-secret
persistence:
  enabled: true

sidecar:
  alerts:
    enabled: true
    searchNamespace:
      - victoria-metrics
      - kube-prometheus-stack
  dashboards:
    enabled: true
    folderAnnotation: grafana_folder
    provider:
      folder: k8s
    searchNamespace:
      - grafana
      - victoria-metrics
      - tempo
      - kube-prometheus-stack
      - argocd

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: "vm"
        orgId: 1
        folder: "vm"
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/vm

dashboards:
  vm:
    VictoriaLogs:
      gnetId: 22084
      revision: 3
    VMAlerts:
      gnetId: 14950
      revision: 13
    VMSingle:
      gnetId: 10229
      revision: 37

grafana.ini:
  server:
    root_url: https://metrics.127.0.0.1.nip.io
  users:
    allow_sign_up: false
    # Viewers can edit/inspect dashboard settings in the browser. But not save the dashboard.
    viewers_can_edit: true
  log:
    mode: console
    level: error
  auth.github:
    enabled: true
    client_id: Ov23li2QCtAG4ZRJF3UH
    client_secret: ${github-client-secret}
    # allowed_organizations:
    skip_org_role_sync: true
  plugins:
    allow_loading_unsigned_plugins: victoriametrics-logs-datasource

plugins:
  - https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.13.1/victoriametrics-logs-datasource-v0.13.1.zip;victoriametrics-logs-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Alertmanager
        type: alertmanager
        url: http://alertmanager.alertmanager.svc.cluster.local:9093
        access: proxy
        jsonData:
          implementation: prometheus
          handleGrafanaManagedAlerts: true
      - name: victoriametrics
        type: prometheus
        orgId: 1
        url: http://vmsingle-server.victoria-metrics.svc.cluster.local:8429
        access: proxy
        isDefault: true
        updateIntervalSeconds: 10
        editable: true
      - name: VictoriaLogs
        type: victoriametrics-logs-datasource
        access: proxy
        url: http://vlogs-vm-logs.victoria-metrics.svc.cluster.local:9428
      - name: Tempo
        type: tempo
        orgId: 1
        url: "http://tempo.tempo.svc.cluster.local:3100"
        access: proxy
        jsonData:
          nodeGraph:
            enabled: true
          search:
            hide: false
# alerting:
#   contactpoints.yaml:
#     apiVersion: 1
#     contactPoints:
#       - orgId: 1
#         name: Pagerduty Grafana
#         receivers:
#           - uid: XTCAjgR4z
#             type: pagerduty
#             settings:
#               integrationKey: ${pagerduty-integration-key-grafana}
#               severity: '{{ "{{" }} .CommonLabels.Severity {{ "}}" }}'
