admin:
  existingSecret: grafana-secret
envFromSecret: grafana-secret
persistence:
  enabled: true

sidecar:
  alerts:
    enabled: true
    searchNamespace:
      - victoria-metrics
      - kube-prometheus-stack
  dashboards:
    enabled: true
    provider:
      folder: k8s
    searchNamespace:
      - victoria-metrics
      - kube-prometheus-stack

grafana.ini:
  server:
    root_url: https://metrics.127.0.0.1.nip.io
  users:
    allow_sign_up: false
    # Viewers can edit/inspect dashboard settings in the browser. But not save the dashboard.
    viewers_can_edit: true
  log:
    mode: console
    level: error
  auth.github:
    enabled: true
    client_id: Ov23li2QCtAG4ZRJF3UH
    client_secret: ${github-client-secret}
    # allowed_organizations:
    skip_org_role_sync: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Alertmanager
        type: alertmanager
        url: http://alertmanager.alertmanager.svc.cluster.local:9093
        access: proxy
        jsonData:
          implementation: prometheus
          handleGrafanaManagedAlerts: true
      - name: victoriametrics
        type: prometheus
        orgId: 1
        url: http://victoria-metrics-victoria-metrics-single-server.victoria-metrics.svc.cluster.local:8428
        access: proxy
        isDefault: true
        updateIntervalSeconds: 10
        editable: true
      - name: Tempo
        type: tempo
        orgId: 1
        url: "http://tempo-query-frontend.tempo.svc.cluster.local:3100"
        access: proxy
        jsonData:
          nodeGraph:
            enabled: true
          search:
            hide: false
# alerting:
#   contactpoints.yaml:
#     apiVersion: 1
#     contactPoints:
#       - orgId: 1
#         name: Pagerduty Grafana
#         receivers:
#           - uid: XTCAjgR4z
#             type: pagerduty
#             settings:
#               integrationKey: ${pagerduty-integration-key-grafana}
#               severity: '{{ "{{" }} .CommonLabels.Severity {{ "}}" }}'
