apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  labels:
    release: kube-prometheus-stack-k3d-control
spec:
  endpoints:
    - interval: 30s
      port: http
  namespaceSelector:
    matchNames:
      - alertmanager
  selector:
    matchLabels:
      app.kubernetes.io/instance: alertmanager
      app.kubernetes.io/name: alertmanager
