apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-db
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  bootstrap:
    initdb:
      database: app
      owner: app-user
  resources:
    requests:
      memory: "512Mi"
    limits:
      memory: "512Mi"
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
  # backup:
  #   retentionPolicy: 30d
  #   barmanObjectStore:
  #     destinationPath: s3://app-backup
  #     s3Credentials:
  #       inheritFromIAMRole: true
