backend:
  env:
    - name: SERVICE_VERSION
      value: $ARGOCD_APP_REVISION_SHORT

volumeClaimDefault:
  backend:
    hostPath:
      path: "/tmp/k3dvol/dev"
volumeClaimPublic:
  backend:
    hostPath:
      path: "/tmp/k3dvol/dev"

sandboxNamespace: "public-dev"

ingress:
  domain: "dev.127.0.0.1.nip.io"
