apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps-monitoring
  namespace: argocd
spec:
  project: monitoring
  source:
    path: monitoring/argo-apps
    repoURL: https://github.com/Utwo/k8s-playground
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
