apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: prometheus-auth
spec:
  secretTemplates:
    - name: prometheus-auth
      stringData:
        AUTH_TOKEN: ENC[AES256_GCM,data:bj9xaxho390d7riR,iv:Wr2+C5RGzTu+id1Zg6dDSNvzGbeDxElLWsOUTbb6J20=,tag:9tYYTm2uvm7MCTkgSFWGkw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZzFJMVFFa3RSVFk3dmZx
        b3RIK1dKV0VLcFlMY2M3WnZTYTg0R25RUDFrCnZqZmVZLzdkZDBWc0NmclpuU1ho
        NU5aRVI5eFdhYVp0QWZPTzhhSm9WQmcKLS0tIFh0eVJXdjJGUlM0K1prdit6SlFE
        RkNjR1NVRkRreGNjTkYxZDV2RGQ0akEKt+Qcq+myewC2XZyd4R+HBV0r/624wyfw
        LT5y0baMXjdoNKLxJBIoC4KKOzeLWFOpjuMdCwejYmr1175/mqj/5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-15T22:22:14Z"
  mac: ENC[AES256_GCM,data:ksRKnhjIFEwNHqNhdmKP7mLsLhHIfNpLw1XUN6J2KFJi4zNrpX/4wDF7QGLvKQlhOgkRu2F5EbT3Be3/7ErRXPZn39JU5/q5RlVbbuLywVk9+C1VTHu2BElySSUcjIMiD/6djWS8BNJ5qZRI9e7PuZ93ZZmfAr98TZCDEvJdR1o=,iv:TrgskRCsZVtstD0VaEfa+BSmZRvbrtNFsXcHErRbIBg=,tag:Hzasr4yJ/SszlbKNVeKvFQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.3
