# https://github.com/grafana/loki/blob/main/production/helm/loki/single-binary-values.yaml
deploymentMode: SingleBinary

gateway:
  basicAuth:
    enabled: true
    existingSecret: loki-secret
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - host: loki.k3d-sandbox-control-serverlb.orb.local
        paths:
          - path: /
            pathType: Prefix
    tls: []

loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
  ingester:
    chunk_encoding: snappy
  tracing:
    enabled: true
  querier:
    # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
    max_concurrent: 2
  limits_config:
    retention_period: 1d

resultsCache:
  resources:
    requests:

chunksCache:
  resources:
    requests:

minio:
  enabled: true

lokiCanary:
  enabled: false

test:
  enabled: false
