destinations:
  - name: prometheus
    type: prometheus
    url: http://vmsingle-server.victoria-metrics.svc.cluster.local:8429/api/v1/write
  - name: loki
    type: loki
    url: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
    tenantIdKey: TENANT_ID
    auth:
      type: basic
      usernameKey: LOKI_USERNAME
      passwordKey: LOKI_PASSWORD
    secret:
      create: false
      name: alloy-secret
      namespace: alloy
  - name: tempo
    type: otlp
    url: http://tempo.k3d-sandbox-control-serverlb.orb.local/otlp
    tenantIdKey: TENANT_ID
    metrics:
      enabled: false
    logs:
      enabled: false
    auth:
      type: basic
      username: "admin"
      passwordKey: TEMPO_PASSWORD
    secret:
      create: false
      name: alloy-secret
      namespace: alloy
