grafana:
  forceDeployDashboards: true
  sidecar:
    dashboards:
      multicluster:
        global:
          enabled: true

alertmanager:
  forceDeployDashboards: true
nodeExporter:
  forceDeployDashboards: true
defaultRules:
  create: true
