fullnameOverride: "kube-prometheus-stack"

defaultRules:
  create: true

grafana:
  enabled: false
  forceDeployDashboards: true
  sidecar:
    dashboards:
      multicluster:
        global:
          enabled: true
prometheusOperator:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubernetesServiceMonitors:
  enabled: false
kubeProxy:
  enabled: false
alertmanager:
  enabled: false
  forceDeployDashboards: true
nodeExporter:
  enabled: false
  forceDeployDashboards: true
kubeStateMetrics:
  enabled: false
crds:
  enabled: false
prometheus:
  enabled: false
