apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alloy-secret
spec:
    secretTemplates:
        - name: alloy-secret
          stringData:
            TENANT_ID: ENC[AES256_GCM,data:vev+eHYe2YTCNQ==,iv:3v731GiKogs6q8VTC47KsoxGRCeMgEa7ZgOILCaoUig=,tag:EXpl42jBZJHLIDZ0j9CI3A==,type:str]
            PROMETHEUS_AUTH_TOKEN: ENC[AES256_GCM,data:eif9u0ppMXHKsBp9,iv:SIOkp6mL2dltqYWHgd7RqZmfgNo1FkSFWV2z8WEAZHk=,tag:rlKWcpyIgAceTFwurX7v8A==,type:str]
            LOKI_USERNAME: ENC[AES256_GCM,data:htjFMxc=,iv:Yk3HV1qNO/z5aCpnzge3Jub35GZnADaVck2BvNJUb1k=,tag:J1Vnh/fFUBfcZSLJRwUopw==,type:str]
            LOKI_PASSWORD: ENC[AES256_GCM,data:sIMAHHs=,iv:AQwTMe2eeC5w53O7DQQ84KYbr6Yl24i7YajG+8VlIyk=,tag:c8hXdUPrqi8vgmjN9my1Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZzFJMVFFa3RSVFk3dmZx
            b3RIK1dKV0VLcFlMY2M3WnZTYTg0R25RUDFrCnZqZmVZLzdkZDBWc0NmclpuU1ho
            NU5aRVI5eFdhYVp0QWZPTzhhSm9WQmcKLS0tIFh0eVJXdjJGUlM0K1prdit6SlFE
            RkNjR1NVRkRreGNjTkYxZDV2RGQ0akEKt+Qcq+myewC2XZyd4R+HBV0r/624wyfw
            LT5y0baMXjdoNKLxJBIoC4KKOzeLWFOpjuMdCwejYmr1175/mqj/5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-24T12:44:08Z"
    mac: ENC[AES256_GCM,data:0qciynhwcW4M8Ex0+D0hg4mkoGB/V923fbmIcm0UyKZNxZ76zIHdMwfvk+3Avzuuz5p6BeCxUVdZVwp93laxfmp1aTa7YmJwM9gaCQnos+0nzBXO7kf3LRhnT9jlfwgBevo8SC+U/EeHcSFC9RzmI2MYPqMOKrV74fl7/WJLcTw=,iv:g5uELxbdbtYKgTyyIG7PTGkxwjUpoO6LHt4QKwRokfk=,tag:hhc/MobXEiWacdDYoNzmcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
