apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alloy-secret
spec:
    secretTemplates:
        - name: alloy-secret
          stringData:
            TENANT_ID: ENC[AES256_GCM,data:h3HeEtbC,iv:mO1eMVD3GfLcAFPmaq3sFnqqi3CbmXAR+2UAoWJFjtY=,tag:EpTA1qgsv1YuKdpo/zjdWg==,type:str]
            PROMETHEUS_AUTH_TOKEN: ENC[AES256_GCM,data:eif9u0ppMXHKsBp9,iv:SIOkp6mL2dltqYWHgd7RqZmfgNo1FkSFWV2z8WEAZHk=,tag:rlKWcpyIgAceTFwurX7v8A==,type:str]
            LOKI_USERNAME: ENC[AES256_GCM,data:htjFMxc=,iv:Yk3HV1qNO/z5aCpnzge3Jub35GZnADaVck2BvNJUb1k=,tag:J1Vnh/fFUBfcZSLJRwUopw==,type:str]
            LOKI_PASSWORD: ENC[AES256_GCM,data:sIMAHHs=,iv:AQwTMe2eeC5w53O7DQQ84KYbr6Yl24i7YajG+8VlIyk=,tag:c8hXdUPrqi8vgmjN9my1Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZzFJMVFFa3RSVFk3dmZx
            b3RIK1dKV0VLcFlMY2M3WnZTYTg0R25RUDFrCnZqZmVZLzdkZDBWc0NmclpuU1ho
            NU5aRVI5eFdhYVp0QWZPTzhhSm9WQmcKLS0tIFh0eVJXdjJGUlM0K1prdit6SlFE
            RkNjR1NVRkRreGNjTkYxZDV2RGQ0akEKt+Qcq+myewC2XZyd4R+HBV0r/624wyfw
            LT5y0baMXjdoNKLxJBIoC4KKOzeLWFOpjuMdCwejYmr1175/mqj/5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T08:18:16Z"
    mac: ENC[AES256_GCM,data:nstb7YYg5J8p+uFxwqF4iy8GlS6fwgQ7VGNx9mTkLVxjg+TkFr7e5fuqu4eudaqGIZB5YPIn1gR0vSpewqmIb/l/SP6uYn+OZKFk+bCZNP3LJ1Eg7wp6w06StnJYIwMBVNZ3egj0oJln9yXzKEMuI2hv2oLmp5JcplsJr110jL4=,iv:LsUnUzclJ55SxQZ+EmNPMu3y0fSBAqYmGBPTmjYW770=,tag:G0YI3+wfYvAXnm7jUBsmqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
