apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alloy-secret
spec:
    secretTemplates:
        - name: alloy-secret
          stringData:
            TENANT_ID: ENC[AES256_GCM,data:h3HeEtbC,iv:mO1eMVD3GfLcAFPmaq3sFnqqi3CbmXAR+2UAoWJFjtY=,tag:EpTA1qgsv1YuKdpo/zjdWg==,type:str]
            PROMETHEUS_AUTH_TOKEN: ENC[AES256_GCM,data:eif9u0ppMXHKsBp9,iv:SIOkp6mL2dltqYWHgd7RqZmfgNo1FkSFWV2z8WEAZHk=,tag:rlKWcpyIgAceTFwurX7v8A==,type:str]
            LOKI_USERNAME: ENC[AES256_GCM,data:htjFMxc=,iv:Yk3HV1qNO/z5aCpnzge3Jub35GZnADaVck2BvNJUb1k=,tag:J1Vnh/fFUBfcZSLJRwUopw==,type:str]
            LOKI_PASSWORD: ENC[AES256_GCM,data:sIMAHHs=,iv:AQwTMe2eeC5w53O7DQQ84KYbr6Yl24i7YajG+8VlIyk=,tag:c8hXdUPrqi8vgmjN9my1Mg==,type:str]
            TEMPO_USERNAME: ENC[AES256_GCM,data:mj3TpOk=,iv:4odU2C4dPSysyWmKZvYbAXXwXF2OzIEqglr/KCRpv2o=,tag:Dnv1b+37hTEJYQfDykO5NQ==,type:str]
            TEMPO_PASSWORD: ENC[AES256_GCM,data:YNSbJ00=,iv:vrdNV1VDC9hD7lT5eKn91Y6ZO9tagrrtFTFqMVht9lI=,tag:FHqPCn0zLvH0Kk6oHDkmsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZzFJMVFFa3RSVFk3dmZx
            b3RIK1dKV0VLcFlMY2M3WnZTYTg0R25RUDFrCnZqZmVZLzdkZDBWc0NmclpuU1ho
            NU5aRVI5eFdhYVp0QWZPTzhhSm9WQmcKLS0tIFh0eVJXdjJGUlM0K1prdit6SlFE
            RkNjR1NVRkRreGNjTkYxZDV2RGQ0akEKt+Qcq+myewC2XZyd4R+HBV0r/624wyfw
            LT5y0baMXjdoNKLxJBIoC4KKOzeLWFOpjuMdCwejYmr1175/mqj/5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-25T14:57:49Z"
    mac: ENC[AES256_GCM,data:dTV4Trsh6tRdQpVX/RMLEaBqQDX58k+lh2PDuyUBz7gEjigbg5gXorSR6shqv3uDri9OvVLoarFNBHkPVKxr/esHVI5mn6c8G7LC9H0GVuY3k+2fPxkDIanIJJuidyBfDc2lf8BLnRTixOmYGw0CEbcLiwVi+HLqMEJH8DPdckg=,iv:dm9MZdqIb89wWpqd1u1iBGgRPLaMJQNgzVAH6LRRG8Q=,tag:m3OaehWOEkRk92lNY8PGBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
