fullnameOverride: "kube-prometheus-stack"

cleanPrometheusOperatorObjectNames: true

defaultRules:
  create: false
  disabled:
    # TODO: https://github.com/prometheus/prometheus/issues/14349
    PrometheusNotConnectedToAlertmanagers: true

grafana:
  enabled: false
kubeControllerManager:
  enabled: false
coreDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
alertmanager:
  enabled: false
# nodeExporter:
#   enabled: false
kubeStateMetrics:
  enabled: false
crds:
  enabled: false
prometheus:
  enabled: false
