apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: ingress
    - name: namespace
    - name: interval
      value: 10s
    - name: successRateThreshold
      value: "0.90"
    - name: PROMETHEUS_AUTH_TOKEN
      valueFrom:
        secretKeyRef:
          name: prometheus-auth-token
          key: PROMETHEUS_AUTH_TOKEN
  metrics:
    - name: success-rate
      interval: "{{ args.interval }}"
      successCondition: len(result) == 0 || isNaN(result[0]) || result[0] > {{ args.successRateThreshold }}
      provider:
        prometheus:
          address: http://collector.k3d-sandbox-control-serverlb.orb.local
          insecure: true
          headers:
            - key: Authorization
              value: Bearer {{ args.PROMETHEUS_AUTH_TOKEN }}
          query: >+
            # generate some data if there is no traffic
            sum(
              rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}",exported_namespace="{{args.namespace}}",status!~"[4-5].*"}[20s])) + 2
              /
              sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}",exported_namespace="{{args.namespace}}"}[20s]) + 10
            )
