apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: github-token-secret
  namespace: kargo-project-playground-sandbox
spec:
  secretTemplates:
    - name: github-token-secret
      labels:
        kargo.akuity.io/cred-type: git
      stringData:
        repoURL: ENC[AES256_GCM,data:MqXFfZpkB87y4KklRIuzoQfkiKFua8VQclQLaJC6+wWWdh3/xAU=,iv:UBKwgpndvEaXBDhA6NEPeI26paLlGTlJNhIHk3wGv4I=,tag:JxSdsAOo+rhx0bajuewOZg==,type:str]
        password: ENC[AES256_GCM,data:CDgdMA1lKmbv7YW0YLNjz4GkdlB7ohP+6AGNWIJh0DSxhObGQkIOL9J/YYAo8D11QVUQ/p1Ey4f7QWjOcsqu04NzE7IeS+51wiZ4TaCP8I+4qGDnj+SGk2vsm4BC,iv:p6leB+jXjh//q6aK76dszQBgKJpO2pf31hmCDoNuaLg=,tag:hF5AoBJBtbEDRUmfHW6gDA==,type:str]
        username: ENC[AES256_GCM,data:n3IvIQ==,iv:GhRhNCgdRQ/YPyum6gJdnOkYgQcN7g3Schx07XQcqEM=,tag:4ds1gdd8gP6LJh47ECWwgg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4dW9tY2tIbVJrVXNVU0xD
        d2pDS0NmVEc5VGR6YkhodlpOcmtBSnphYmxrCnkreFAwVmc2Mi8vSVRBV1NXa0R1
        K1RSTWs4eWFpTlNkU0dPL1FBSzlIN3MKLS0tIGx2b0JPVGV3ZU5jYWRQUkZad0pp
        MHpjM0JQRENjY3dVL3dYdWdGb0UyZ0kKxmgadowwMPcFllN5Hj3l6w+B3q/bYD/6
        CRzr3co1dB5D+POhdv0JsQUugvj68BLghM8kujquW7ISKjZ33Mj1pg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-24T22:17:52Z"
  mac: ENC[AES256_GCM,data:xHTZyniHihI7CYIxToRym47hc72vD0RiUVV1YZsEdmaTimg9Ec+y+pUgCJTcLDdrz6m0Jjy5KMzwuBCpGCUI5F/WrLfYNoqNx57MVRtbD6lWdEUHACG1CIIrqS134tdx3BI2BDVeJ3dt+jGahtZVZQaPLxePpjePbuzk/2jn3Ts=,iv:RrODneCRfJ/cecMlLwfqbYwugUKMhnHHn6CxybwfWT8=,tag:mGwdn2RH5t5oyChlqQDb0Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.3
