apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: github-secret
    namespace: kargo-project-playground-sandbox
spec:
    secretTemplates:
        - name: github-secret
          labels:
            kargo.akuity.io/cred-type: git
          stringData:
            githubAppID: ENC[AES256_GCM,data:eWukT3U+xA==,iv:24bWIa77ttiKFKydCpbcZAJSKL8/fjWKtA5qOjz/guE=,tag:n7LSY38OzkvhsFHB0EPayw==,type:str]
            githubAppInstallationID: ENC[AES256_GCM,data:s5ybGo6vxaE=,iv:s+xDJPrqykQa6V2PvVwWVxY4HXQPR4eMWltEsfaWNWE=,tag:MUBdvSh1vV5+0jVcQxECTQ==,type:str]
            githubAppPrivateKey: ENC[AES256_GCM,data:Zm0O3T8wYqwViAP0qXfrx/Lc0dsw8/VxsqTE78AbkT8nQUSM+yM2uF3lUrFNoRE/MxSLgOtnt5jKZsQmyCQ2O1DEC/1kBk/FTAyMtXRsH3e4Snxc/syXIsFto5Wb7/hZU66A6gotHYDGUXkys40ozTxf4WQx2Toe61r8IoLSk1R/4ECdUbUQTyHp5qxJsAi2RfP+wCEbbhp/kFeh2zkcLTmD6s59VpUtrFp8N4hCwRfxaRYDrmfiSDmcNtWb1QWXGgMplg6w30gWABjTd2Jx82aJAMfnUO510Q5k5OPM9hoanaQ4NJAOFVJJtXEXMsL/fbxDL+1WXigApAb73y1kUPdFXGKqRUdUVe+/gAG//cafczqlIZGx+twlNFZKw3icrhNFkl92f7cq1ut+F0s4l9UBjG2WOcwxrmId9GKtQL8d8gmTCP22ekSmyf/Iw7/4/Q+EZcuOnd8GMEb7oCoJpFsdttlXHiX1zf0IZgxbqRmAz+0HhCCClGuQmYjWrYjyTZuvNmpjPbwCMASA2S59yPix8ov8aHTZrs90DZQnTblMyIpPzl3pZK4S9U4wy6YdrZR8v2vyOmsEtaW6YdnwvSWnhH7HntISiGKt6KdkrAu92oNe/waCkjJp7RE+Pr2JjB/PiEtysVWOyQKMcdp9pE95cZqnmxd/XsxUGxilZ45OdoeOBqa9Lrt/m3pQbm4xPYYSCCIGSvudjobHd+pQLV14dqpM9y4QpW9g1/tx0kHjW5js4ZMOkQhFnHwsqfShxxoab5YngfvSKVHTml3U6vKGUoCMzgGzT+lj/Y+Z3nfGAwmaQWQ6BLT9Gwz1LzIFLBBizhZFcTO8XyLt4FTqKqbi0KQbZkfyE1WwGq7gysc5PpYenrziomR4Mu6c3oSKFPf4soBF1xSj8BtbWVSQME66DMsbZ+mACYzp3y5dRJMjjXkz5gvEhjZkPbgUZqP0NDsVOEOAcd5+LxP+L4PRAAMrEhdc/LmLEUWajUPJs4lLgfY34w0lBky9/psPOdj+dauxE5VTw9C4rT3u9CdRAsH5rVPm/L/pmfBkHijSWa2DbDtuLdxqzKxVN8ITX+wlN+oK5BzqGdKLdXQvzRfaQj4W5GvK4oW1q5+iejRL+f5JVpbY4784C07XVmdN8uRABM0tCeaUcLBgVIyOxIXFUAKVK74JY5NwRBD+nQSgl5JZQNhk8gjROoGdrruRr7HBgLBDy1K9M3VrVHEKbj46SRP7h3si/A0iFVA7HWAX8uwEYUzokia71UgmmvaOZ6kPZheJhx2D8Y2VqTLWZW9k8tlgBnEE6djz04q+WUGbMc4l0hbp51SOKASLh6Y5kLJT7ox77IYIm90g30txT16TGFWZQXFqQxHsLU0Nshgc3KF/XwhWEcYkv8QolGx84VC2C6So6m/lu87P2l49az/3uGvNMmMwJTiBE9yk51nYu6rNG3+++fKJHLXEbVnlqRCyu6EEadueEBj5o1uke/swB7onX6q3COHH83d9qLkjoWA/0p19Wu2VR0pxeIRlXVra4amjogIOHBDSLb5Dyj7OCo7hoA91ftWykJxU+SGIW9HCT7Bk/GDHzXMX6oKPCLoop256YwHcMu/76wnyHY+lj6MH29Mf/yLXvnMQEOu4ZKJ4JmbazIAHWa6/qQMrH63XtGVrR/65APM1wpcdT1yLQTHuRJ40Uesh4Y31HGbYV42CI3I1pMNDP8HVycXwGN1tXgJtzH9O5FMNzzOXLb1tn0M64XfFefI26G88j0dvCj00ZH6ZbYiDau1dbhB8isS/irJUVbf7vSZgGz9uOgGQYCvzgjMJlsmc9JZ5cr16dMgo32WLx0s9zb/gI717M6lxpPr1sp0cnkYEip0oBvwR6yKDDO+unNz7D9I0RpN6UCUAdKsb1MA+7wMuWNRlkvuqwJesz3C5DVMtqnW/N61TOPGOakSNgyBNETko+jWovWSztQvUr8BT6Ecb2kDKNNZd8dQn/i90CIZSRjSCijABG8rAerjTN7c5vMu8OQo9YbBPuvTJsZzNXgGASpybIgMMr1HBiwIpCKeR6bNhewY9xMfG9zp2zyRKCtqhGledqoy592M3POwqChf7HklwapLLTTDdXifykdQuaMT1/6gQYexYN1FD4o/SnFXrn/S706ZXg2Lt3biC7YgPhSkQuzppJ0sZovum35Ci0rXWF5fJ8NxnlDSx1w1YKE5zp2V4Ryjk+5UL+zqzaAFN,iv:41egrOFX7n6ZSuEdSf+XSxsB3GlXq6TQO3AuK5fNiBA=,tag:DlM/vWY0FjPy5snuJF0JOA==,type:str]
            repoURL: ENC[AES256_GCM,data:0OiNfxT8uGQcL04/13QZvIjMElq/saoG5ZrGW+G3UF6xEPZke3U=,iv:rTg1DCG9tA8rJs3VIfWgm9w9B/UAQTVtojDdFtXV3G4=,tag:t3p+jyHFnD78iH0AUTiXNA==,type:str]
            #ENC[AES256_GCM,data:9LryUa4R0Q92wITmcXkpA2ecMNXbfVE=,iv:bhHB1ElcHpOQUD9F5D85On1R2IKtZDf0L5/dq+8+gJ0=,tag:msdiIC6S6fwS9j3IXErxSw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSmpJTXBrQzQ4c1R1ZGZK
            Q013MlpSVFVFNlNuZXFPMWNqb3BqdXdnRXhnCjJlak5McFBwYmVJWnBLVHkwdi9l
            SHVRNGw3QlA0MlAvK3ZVK3ZsQ3o5UTAKLS0tIGFQR09QYmcvVEttN2lSQkV2a0RZ
            eGtvVHRiSXk3Zlk0WkVWQWdDVmZjOHcKYslWC99B5tddmDXBfbKtFYIsw7F24zXV
            UPvfuMdA/UvB1zCjlAfuw7sMAyDA/8lWi8A8GgEwrUFuml+/fpxGtg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T22:05:52Z"
    mac: ENC[AES256_GCM,data:I27y/0C2GNjYM+5wxEG8FYUmhLlaHtAlXmeOPBzThUnXArOx/T7vxJ/x2bKBW4khgDuFVm83GY71mPCxDyIg+IXObU9RnKJ6tecE+44Pcrlpq6nocZMa6TwlIg/u/O4wKms/PeigTgm6Hk3zq66glPrgxk5lKsZpiGaSQr1NtVw=,iv:wZCuoQWbvZImYRv1HDt83ywh/nsJW58f8i8caFcqeEE=,tag:BUkfqB9zDIDwz2P1JCam6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
