# apiVersion: isindir.github.com/v1alpha3
# kind: SopsSecret
# metadata:
#     name: github-secret
#     namespace: kargo-project-playground-sandbox
# spec:
#     secretTemplates:
#         - name: github-secret
#           labels:
#             kargo.akuity.io/cred-type: git
#           stringData:
#             githubAppID: ENC[AES256_GCM,data:eWukT3U+xA==,iv:24bWIa77ttiKFKydCpbcZAJSKL8/fjWKtA5qOjz/guE=,tag:n7LSY38OzkvhsFHB0EPayw==,type:str]
#             githubAppInstallationID: ENC[AES256_GCM,data:s5ybGo6vxaE=,iv:s+xDJPrqykQa6V2PvVwWVxY4HXQPR4eMWltEsfaWNWE=,tag:MUBdvSh1vV5+0jVcQxECTQ==,type:str]
#             githubAppPrivateKey: ENC[AES256_GCM,data:urUKtWrzJNatZapNedNS7Nm5O554RwFpu4wTPL+EjoxOgFl3i5ANrKOcukOkdjykU6i5j+1mD9p8A7VkTmWNw3GW+CBERVBQ4jcCMwCXh2oimpl8cDKroBQUYeBiLVCzh1kx6L+EmxtntCcPb5DeRSnq5fevPkeetPASg1YjqARKcabi55Vw0zrTX8y1Jzpw4ZdsMFtw57ShMSU4mYruPZ6RklaZlB4OZlwMDX1vBegFxuCl90Tyv9xoC9TlHZsmw5enX0JzFcLFSzYsQTdL7nLJgB432SAdEUWme5o3MYr80di8m9XDbi3fdTOFT/V3bcz7Laaeay3TaGD5RO0o8iXmp5OaUrChkW1pnFhjGTy5s2M2eblw9676igJPFwQL9fi3AYXlBbVfai+ySvrnOqynIUA+Nqqq89cDxZnmf27gNTFrTSC+ITX2gSWw5KyZLenemfG19ag3JMJmz11GY6hR+P354bbtTPrxOSyTk3MOzF0agsC5JNvsbIpKVHYtGu8pGBLudD5SXJrL9HAkI29ZxnJq5s2h1Cz1c0Cc7qiGN6mTDpeSZK0SItND6ZqYUKMdzQYLHLzIL2r2nTWes2Itz3RND7ZJWsPEjQFUGISJFX7r40pHuKGgoRcjg5H7jf9ST7t4vlVk1AMcaS1+heaOArpRb4jPx1Kc9LNLwfdMqAadcYB133xRFTYptRx3F9XEEZmBY4f+4UPI9mZ/I4mltBhSnTc/ja9ItzsxK0xBjj0AXD8bIHX3sajjpr6V0DGJCxqQAF9zTyslSzk5hmllr1HHTqBGaV92R9ID+11qZkn1Y6zfs64q6fP36lKVqdl29bxIx0QhYFHbDCIILax6gNxk/jPEY/Ctw0iObEII9PYvTeO9PMp1zhrmhoYxrbR//gB/kWuH8hbN+y5gD5/B/0l+QYmrB8FmmLz4aUTIVfp+7gtPLtzKetUSq2kW+SpVs1J88BKoiTIh6w2TYaHoYDXI6YFWQBi1Klj66iD3Lg3NqRS5/L9MwMjItNgFaRpfWhDzK8yrJ3HcnAcjASZPZMUGJqsBaVfhhDHO7lEyDjmcgSXxpKCTyvJi+EdPRMUyO1+ziMU3JTfURs9RSZD3TqCzWodKjM7K1WI6z5gEbZoTTSmo51rJzPa542/vzSDC5n0njqOZU2mDMmCHYLzU/o/v1h+FddsAOjO5hYD/rmYysvljNU0oJrCK47pi05H8wOdZ79/DgrkJ2U6cbnzLoMsTfqffOznViOjMlnM3L/41Sc0mKc0lPeHLWL1QC4IBCuzO+jQgxkSRmQKxSriliRmtrEJn0NdPiuIV6ZZ2a9wjAmmI1uYEnqiY2/x0eguVQM04P8Now/KQlSi5InpQsOBlzB/x2ncgqaSWL+sCYHdDGecTur3hcsq30ZqqpZt/ir8HogmJWqgTeqnbZcjwYf41lvIwEqg2hdecy2y5a0nRUDOp6w3ObjlZu5959TvqOnnBNGDHAeIA4XMjQyVeJeDhHP2DTh/eD5BwuRr3arLxDePo9PgN8IgzDm+WqTUzu8J2TJtH4NZOJlayxITSubMGrrh+x8A21fwMzp9wsjFu+zX+VVyNw3JEZObFPjJ0PH/7Z4Bpo5z56Mmwx6JF/8kl5jq4a1klSqWEktacxtXFSRR8czxCjyFyH9vUazaw9Ory+z+T6q+voYXjwVD9JPQpxQQoq3MhCHgnXauCFtioiQhCnRI1xMkiwZHuf39TldKKh2vCchW5rVmGoaktIT7XQTPdYk5+LhYIcKBoKSXbFTJdUOzDCDNH8VlCrqPWgiBThv6nH0WsrP3LiwT947+Dq8//LGyttCRLIteCbcFR7lTnAInmflQVtkix01q0P77e6KmBOijJpd0T9IKC9dxF/EyYyE8OTGLKPBkT7u3jUTw2IfAQdE+k+fln6ywJee5z33jWSJLUrPZF813heO7pBcdmhWOJ2W8D5kMIDSqYOOoVTXSPqsiQm11L2HKYBAzH3miMkM6qR3R8cZCbS2FWRW10frXCb9n8JdbJRc406VlW7PTXzmcEpGBXH4Zpahn3rB9r4AhhIbG2vBETnJ4GdtNS/Q1IGbgSxYxmqO/MvScTMIKbZeQnbwXn1tNdTbdmot0mk3hIt9I7ZdjqI7PBN2IYZ1gyB4q/8HMdyyalUCc8syEll4K0qgxdTNLVsbfPRYPhmY2vHuQ0DjwZhoUaSgMjyI2K8ktaTbfH3JuHLb9IFcegSw==,iv:qvMQqVDAV2W9IySL5jY74tx5JEJG7bHCiV3sxnWGIio=,tag:ozjXG7QIntCHeS8CViBYVg==,type:str]
#             repoURL: ENC[AES256_GCM,data:0OiNfxT8uGQcL04/13QZvIjMElq/saoG5ZrGW+G3UF6xEPZke3U=,iv:rTg1DCG9tA8rJs3VIfWgm9w9B/UAQTVtojDdFtXV3G4=,tag:t3p+jyHFnD78iH0AUTiXNA==,type:str]
#             #ENC[AES256_GCM,data:9LryUa4R0Q92wITmcXkpA2ecMNXbfVE=,iv:bhHB1ElcHpOQUD9F5D85On1R2IKtZDf0L5/dq+8+gJ0=,tag:msdiIC6S6fwS9j3IXErxSw==,type:comment]
# sops:
#     kms: []
#     gcp_kms: []
#     azure_kv: []
#     hc_vault: []
#     age:
#         - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
#           enc: |
#             -----BEGIN AGE ENCRYPTED FILE-----
#             YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSmpJTXBrQzQ4c1R1ZGZK
#             Q013MlpSVFVFNlNuZXFPMWNqb3BqdXdnRXhnCjJlak5McFBwYmVJWnBLVHkwdi9l
#             SHVRNGw3QlA0MlAvK3ZVK3ZsQ3o5UTAKLS0tIGFQR09QYmcvVEttN2lSQkV2a0RZ
#             eGtvVHRiSXk3Zlk0WkVWQWdDVmZjOHcKYslWC99B5tddmDXBfbKtFYIsw7F24zXV
#             UPvfuMdA/UvB1zCjlAfuw7sMAyDA/8lWi8A8GgEwrUFuml+/fpxGtg==
#             -----END AGE ENCRYPTED FILE-----
#     lastmodified: "2025-01-24T22:08:09Z"
#     mac: ENC[AES256_GCM,data:TJr/OtvRLp7W5rrp5lEFm8/XtSwMpZx08a53hWVhCXG/9e1rhtXNNFS5Qcr4C0V7uDKDoQ9PVeKoL0+u4GLYnWRL91W1ikQ0Jit462bA220OkBmNcDKbEo/8qgwcEhWggl8vAsGqzI2aQgPMEgm5wRhaU+KcIsNYKNFGVvaXaYI=,iv:dB7rI/ziaMpQDVwVon1V5kDSJkbrEyZjLdP43cKTzTQ=,tag:y4v6ePfZlkTSkrUsv2wUmA==,type:str]
#     pgp: []
#     encrypted_regex: ^(data|stringData)$
#     version: 3.9.3
