apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: playground-sandbox
  namespace: kargo-project-playground-sandbox
spec:
  subscriptions:
    # - image:
    #     repoURL: ghcr.io/utwo/playground-sandbox
    #     imageSelectionStrategy: SemVer
    #     allowTags: ^v?[0-9]+\.[0-9]+\.[0-9]+([\+-].*)?$
    - git:
        repoURL: https://github.com/Utwo/playground-sandbox.git
        branch: main
    - git:
        repoURL: https://github.com/Utwo/k8s-playground.git
        branch: main
        includePaths:
          - apps/playground-sandbox
