apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: k3d-apps-secret
spec:
  secretTemplates:
    - name: k3d-apps-secret
      labels:
        argocd.argoproj.io/secret-type: cluster
        certManager: "true"
        logging: "true"
        monitoring: "true"
        sopsSecret: "true"
      stringData:
        name: k3d-apps
        server: "https://k3d-sandbox-apps-0:6443"
        config: |
          {
            "bearerToken": "<token>",
            "tlsClientConfig": {
              "insecure": false,
              "caData": "<ca.crt>"
            }
          }
