apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: k3d-apps-secret
spec:
    secretTemplates:
        - name: k3d-apps-secret
          labels:
            argocd.argoproj.io/secret-type: cluster
            certManager: "true"
            logging: "true"
            monitoring: "true"
            sopsSecret: "true"
            ingressNginx: "true"
            keda: "true"
            rollouts: "true"
            trivyOperator: "true"
          stringData:
            name: ENC[AES256_GCM,data:9exv/ld6rZA=,iv:9N6qQyLWvijt79A2fOzc9o/fpwUCUx2JVFMq1GFkKX0=,tag:RvLcIQ9lsJgdqjs+lPRNfw==,type:str]
            server: ENC[AES256_GCM,data:/9AHbxcjW3UBv+j3y+AjcT1iFIjVbvybbxZGVEzm0rr6ZEEqMsw=,iv:x75RrCQ3FREKm6ZGx3mmMsgbyT0EXeBuDJJegwCjFos=,tag:iUPmbMYWfc0DdU3+w++0TA==,type:str]
            config: ENC[AES256_GCM,data:Re9ldqyJeKQxC7lxtV2cA2InXSQ9Pt8nWttWQIEgWPVw3lioqUCsM6+1IBqOj5XnCh+TDe4pdfSahCVUmifeVqHaxkkh7OzBQQwyLpqkXlpimZo+pX9UIOFBzJ3bSZ4f+5RuT8R+yYelnSVs6QObvccEoRxZSMMTMyb1DvtwKBVEqM5hRbBThrTs/w0sShA8D+ZSkPpVPL8oSgFAD0vQ3gpHEWejyJYzb4Yk8MkIwcJYKmQYH16mzbLTgCc3Tw3b8Zl3HStw1g//TsT7ewObHIhQqzz/CkRioBa4MmRpqWe+oB9uatbxhfdl2tyQNcJl39+eWK1C7xNxTz6Y9Y2mK+1HXDCCaWuxHiT0bZyM9C9UjN8WdUKBg8bojIYBveDTzcZev8njAPmXq0ElcxgKWpkBc82SIuJ6IkpmzmR1eq/DERENMMhvrJqtxiuLjn4I6yJjaGrQe7S9G4bDkU99o/X9cZBuvg1dDDkzZOaFtq8rPTfJ3o3A4yQiC2zBEnZ8fE6GiGldW7+hNp//Abjr4uWo77KEMfB+lI/FC+UQ4U1d9DOIbP8rIgsotKZAJQ/qTfYmcUF+Gpz9TlXX1YFhdrdK1cBUtt9DIbHc+MuL3nTZToclA7i3Pj66+nbbK54jck9PlFjFyoeCQu5MJFgjCgtmPKL5LjMv7ir9H4j87bJJomCj2XfYyduumcGKakUSmouc+oWfDIsAA8et9tKsGzxsY2c9hJxUJpevWLos2iShfDw9gx3YJlaYaxqphKRkdhZevMUncccgR/+SmN7SaZo+bySvQ74GHDiC2f9RoyEAl77/6IUfKlCdVbAKJCI+NkH+J+gX/RXG10lMWBia0TnGk9jtDY8WXbDfxfC7W+acfIKB64mVfc4wYqJlqx5jh9T8qaxfv9TKM8CNfQSnF8I/xum6fl5ZY2p5L6FDvtU4NCIXSFkUfCYJVeHyQ+cRpJJA7UnQyuAU4onBUHwl6GNB5u+bR05V0ZUUunfBSUtICbDuenetvqGL45F6X/dOp7wxSyzXckVobGlRKfRuzNw2lWNyph9k7zEMGbsgnX/qxmndmOQj8/Tx2MPoVIWn7M0nV19YDO7TyboiliAYDBX9/yRk565HN3LI83Wb+5hRrF7CXDkhe2NF/lof2Wv+DNy0aCOfe6OFIxV4ORWa+7zU9W2InGNhxyUxlZyDq9Hkedfhj1hNEGyTeeiDsSsf4DIthKFderGEFYZaB98QsAWh7HST+mYo2M+jYXtm3bFUx79R54YpuXH9D+Sw2qHV084ivwuJ2HAPBdYAYzRdkIZ6h+Lqfdf9OfILunzIskNNfdT77X3mozr1uRH5+CQV/sVRsMvyKlDuiMjr7AnH2RnnUg6eqt8MqVdaAka4DsrGLKJI1n+OMbiDiRhrCow5cgxWVkwkMOOwvomH9KwI6YxG6XIpOtm4YBf0mdbJ1TKr3qhDkvXM+5E8tEF+k9tXUheb8PZ2+G/qsf86OapbnMNVAdb1olsxZ7wvz00n/RRW1su7slL/1bcS9H7Nl96rlfIt0gkr9MZdnONnDfG1AJE2KVmYPK+X1ENOlYvSGJzC7uNYIXTrbfDyyKw0nLu4FuXS+QB7fRKJA3M4zMARQLYIUkcaCo6HJJ0utw/6wKglhvWzQr1HnCZLwYlSSUoXhLFmxOJ5w3Xi1uvv29f5AvWeUr1ujeqD8iVSQHaIkYEATL+RxBRhJ64cJYCdqWfyvcRsz6CbhFCWJbeluXhgtiJ3ZauSYRscypwixMDdDMG8u0hAaw14pZ4FhbwoRspsnFxnUOgNNuL58joSpg7J3ieEcscinD3aceBb4M6u3kewza4EzjIlzilDIygGgS/a2E/8u0rKXTtnFYzDSqRz/rG5ab9pk7HTFCzVvRptxSdFNv9SRn4a8+6TtCQnSte6r0uVoR/bUYiQrtZonYZjfStOfYX/+dRwTRnh7iw54aBoOau6pXXRGMS1JAXk3ppuhADeXoM2X2RmekNH6sHdlr0wr232XPMkRKQTTIADiZ7ofms5fahZut66kL2I7W8a1r5pg58tjT2ZoDRrIwa+9kLkNkzV+pspzNu1x/aZElnrmckxceSChmRdsqE6MnKbOPlHwtTyWD9LgD9WSbCpM9EWBSUWAPGXx79Fd/kaqd5XOhoAiLmXuD23jmmNgF2zDAITh9enUYWstlY+lr8RwCnmK//ckdsoijNFR9wSgRUIRiVTpfJY3GVybLUpXwWBGdX4jVK2xudLBVdmjvIGGiDz1D6AWK1V1YJl98rQnKRA+gt/C+zn8qxvb0GXp1F0LRnxfb64P+9188aTSgmS90f3484AnQoNvzIQ7WwlnhDtnwF7957G3d4N2CMm0Pl/usPheXFxZweEJdarQXY=,iv:1ikz7fUZeQDQpF6PWrXc2bzqhHwjGoO76Bf4GKmzScE=,tag:ej+W8wgmgLcxL9cLmp1aVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeTB2dnVMK0ZkUkhXMzRT
            Yi95VVdRYzgxSWtSMnNRb014VDB1NndnUVRFCnhrZS95NXVFQW0vMmY2VHhIUE05
            b0VFc2xxa1JJckorUTBPejlud01iYVkKLS0tIFVSM0grajhrWU4zU0dIUHdpQkZt
            eVpFT1pHMFJPYTNtTlhtblFzZzJveEkK4ihkLkZFN35QcvigsTod1OWQc19Ozj2H
            95dh6IL4ROKug3HiLrcQwItsFiKP3+u+3RKx4mQN3CBSaM+ilvWLQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-21T16:38:11Z"
    mac: ENC[AES256_GCM,data:uohaSTp7n0GGRPdCa5WEaDrk0pVw++bUljI4aXMzHIUwW+4VDMYSGOl20ABADb8owQrpHBXuxwMOHS5otf9vR36lmEk2WPp+E4Cz6WGOWRaZKRmRPCKo+Sor1wobISZidw7PjfgC7xr86RO0TGrrVE0q/MD4mIOVIXDcETJogfE=,iv:ZSvut7GLpKnHLLxjQLqSPXeu/Sk7jl3P5VIrITxsU/Q=,tag:Zka1ZqQQsAxJEAiBTp3kkA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
