apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: k3d-apps-secret
spec:
    secretTemplates:
        - name: k3d-apps-secret
          labels:
            argocd.argoproj.io/secret-type: cluster
            certManager: "true"
            logging: "true"
            monitoring: "true"
            sopsSecret: "true"
            ingressNginx: "true"
          stringData:
            name: ENC[AES256_GCM,data:9exv/ld6rZA=,iv:9N6qQyLWvijt79A2fOzc9o/fpwUCUx2JVFMq1GFkKX0=,tag:RvLcIQ9lsJgdqjs+lPRNfw==,type:str]
            server: ENC[AES256_GCM,data:/9AHbxcjW3UBv+j3y+AjcT1iFIjVbvybbxZGVEzm0rr6ZEEqMsw=,iv:x75RrCQ3FREKm6ZGx3mmMsgbyT0EXeBuDJJegwCjFos=,tag:iUPmbMYWfc0DdU3+w++0TA==,type:str]
            config: ENC[AES256_GCM,data:H5zYqCIYfzE9PgH2kLGvNPMB0e2bIoug6x3QVLyeBeZwpungGmC+CW8PyPOyHddBYinEEoS9Rjx5j4BNLzfcwF3nygN/ugbGF9EPwWa324QS1b0Ok5UcRfyn/DhMt34V3g5Qrs/d2mLJTF8FZ7H5AJ35UhReXnurKvnD+66TQUlZg4uDb2fFQBktvTtGwJkESJPScIexglaqa3wsrO5RFv/+l3KzhhY0YiT7NWUWWnd/GYYvWyP/yhYaIOCClO1cbBFFVEOtWPOhkMhDSzA9sqZ+ZLjaG4nwOgvABY56xJ2EhmUOvuxai5sC4E/MpQUlVcIlOhK90MJS1UoiIIQ7Bz1sy64rQKNygBA+WVWWrCOTCPyZGpkYQdgNz6FMdpDO4GhoiVB+Q1CK/1gKP/hWhVf8EXa2UJs0HAIwh60qTZAoR24Gvx0UJvxV9Ubcv+1M9+oA4VcjWv2UrAz+COOKbh70N86vlzClQIfK6Zh8UpvQlaPP41+uyoOjS3odgAuzws/3wLKbHo4IWnUbNw9QeFEDRNO1hkvZ+DObYBrLlgrlMWZZIOluO8hpJqlO0VpmWHhSMf5tx26by+aG5YFznf70HgYbTi2Nmq1097NRNNNIV4gIeHYqKhX2iR/1S4qtz8v1iE8vccx54daEjwIWLMvUgAqlEIUT7Vzsd/BjvDQ4fOmAfLxKPrHRQcW/zoJi0OE2gml2QrBzVK/fhJ86YvoA0VtMFgpk1x2VgbTt1y8+UALtAJP91HwZKUz5H4FD6Knz2luFcbDF6A9GB/qwlgc5wQqmT+Qy2l6UY3EKr5AgHkuY4kQPb276VaN61oxVLJM1ec3OjPl2HOZXFXyZci8YWf54PiDLnt/fa62TYcnHUaXqTuLQPvdoEE4231IdidS0oHxfUIMno1FPLk3GYdfwqbTj6y8f6+HbZn8Up/O1ZHWQIGr/vuf3N8v/Osiad9Cs48j8UzMjXHmSRredYacdsfY6SSXfaKFW665zPS+bq31cQ0Zsq12SaL0rMa5nx+L7SeB+0fgboT79DUrjg6RT5wr/upR84SCOzfvWvSwmRUAalZudK3HCal3gG/z2ca5zDaEY/YjS2W73JHMy2ST9ToOYJ/1P236fJbNjCOXVpn633wG8YR8FU8AYT0wWcX0f80NL9lwPjodYfadkTDPK9wqAJlFOJxmYTB0QOF6H5wONTyDv5UHYGUB1Hyvd3OKnPzCca47ie2ESsu9NFZhewEWzfcV5rpT0CRh97NgLyJB/BMWwohJjQH6EUmvoYk4PGw88266H6bB/tbsorvBFxWHNSwuDii06ue33fuAAj+neSa9E9J3ooQfUK7BkYhEaw944teUMRo4QkIzw9UkkVWi0wI+o5Oe3TVqAH4DrWFoOm2phJ0JFU+mKo5QUsA+K7y9N1NAVOG7Ic7Qx+dSCE/bmriC7kJ5QccGAUaEOsncLOYdqniDNkhmvHpI2GDzHnLVb3x/oi0S7yHkDV+vGnz9iqiNe9TBB0aIa7IsBzQHjnNZZ8O7/qp8mPjSIJWqYO5TUSDcY54Jv4kLKQKzrs5KttptMIg/lgcw1AWSuhUBUtFtyXsk7HWF0FtVUiGAGyonKWWJxfyMgnTo8bp4fkqSv7/Y0GSEKe/sSpEoijP9/+3VESOhhxUAyu8U8MQaJHcjGjJ5ZBJYqssqX67NtFeFooAC9ikL+25nRpY/bU/R37q4TwLwQxzcfgKBd6vFghs7WsrWxipJGrWaDZtsI4eZahyiSv+cg5l7tRZKJ3h8xKGGDXO/ImExVns/GlwJ3IIte9/nJxOPIuxyO9EeBv2lzs9xS5Gl69yldS/YjlRBsPlqP18tKjUDZbOx1oDDDAmjqnd7xlqWsLNw4KL6B9UWe/nlQ5wt++ZyC56Gi8oHpuDBWkvRNKlOirZZc0XfK5TdvKR+kA9uCqMywCwMHGE6GM3XPnfvP2bmdllCnIUqjAGJRVZVMujKspbP3qHdiS7DYmxd4UBoh/uasgOCL3wI5Vq++rUPBzxm/HgEF/jWiifQnelJMeeChlNhH9E3WAO+OrZ0ILN5NSKBdqgOqhcTaWMzepUpagOZtDCpHjl3uH6OSN2Xhi1zlz1h09Z/eYDrhT0LWj+zDqRQ5/mRfKIFQhkB6ElPpA2rEQQ+gmhBDArE8Ci8I0lVz9qrto+FgXQvbwZvo5utfoS+Ga04BoQEUQwxHRBsMHsqjUEvEzVCzsCfDc+0kpxb6mf90RTU1DVQedRrKMR+Mu2Ux0Og3A3wIvR8VT0rncdPuzjCDgBs0gGAyUDh3thLr5kQriW/4KGgjM3/fxEIs3XiyDSjNv5WX+NkHNisP7XuxuTsi2rlBMBu4kpvIR1r/LhEm/5fmcXheRIFxCLwg+fc=,iv:e76Orxk9J9lEVRKXa8JuZ23+EBlXcjPEAhE54GREF8c=,tag:TWIfxGH8X7u2IJAYwzfOnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeTB2dnVMK0ZkUkhXMzRT
            Yi95VVdRYzgxSWtSMnNRb014VDB1NndnUVRFCnhrZS95NXVFQW0vMmY2VHhIUE05
            b0VFc2xxa1JJckorUTBPejlud01iYVkKLS0tIFVSM0grajhrWU4zU0dIUHdpQkZt
            eVpFT1pHMFJPYTNtTlhtblFzZzJveEkK4ihkLkZFN35QcvigsTod1OWQc19Ozj2H
            95dh6IL4ROKug3HiLrcQwItsFiKP3+u+3RKx4mQN3CBSaM+ilvWLQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T14:14:11Z"
    mac: ENC[AES256_GCM,data:ZKSnBo2CvTErxDrM1cDLi3zDbaRui3eYGU6p3Tu3aWONhKw3ViNCCElNwY31CVBfOzyCxo+vFAZpS/g/3y+bIs98iG5N4TYuByo2B1DUStVgzQO0zkuXvxxAJMR0qZrJ0o4PH+TSjLqEuyBFwUqwLDouZ8wqfjFxO7f8u4dJLYA=,iv:c7GUpOduRQuKFuDD1F45ZOxva2biB5SlHKOkHJ8YnGo=,tag:E+R3vW6fVS+TvepWz+sJ3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
