apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: k3d-apps-secret
spec:
    secretTemplates:
        - name: k3d-apps-secret
          labels:
            argocd.argoproj.io/secret-type: cluster
            certManager: "true"
            logging: "true"
            monitoring: "true"
            sopsSecret: "true"
            ingressNginx: "true"
            keda: "true"
            rollouts: "true"
            trivyOperator: "true"
          stringData:
            name: ENC[AES256_GCM,data:9exv/ld6rZA=,iv:9N6qQyLWvijt79A2fOzc9o/fpwUCUx2JVFMq1GFkKX0=,tag:RvLcIQ9lsJgdqjs+lPRNfw==,type:str]
            server: ENC[AES256_GCM,data:/9AHbxcjW3UBv+j3y+AjcT1iFIjVbvybbxZGVEzm0rr6ZEEqMsw=,iv:x75RrCQ3FREKm6ZGx3mmMsgbyT0EXeBuDJJegwCjFos=,tag:iUPmbMYWfc0DdU3+w++0TA==,type:str]
            config: ENC[AES256_GCM,data:OzxVP7w5/aeRrVnTMcdnu0mVPhSevPYyZGZTLW15l4XT/ADfwZ+V6q+uI1kFIvkbDTbxhX/D7ZYcUpqtAqS0JnJ+P3G6x86og31UE6+lzL07pBhMS9SALYwLETmvsqUwJVSpihI9YrqOAkv2slEKin1VO5lwSI/u5RQs6We9x+zjwqxbTwpFiRtVHtwHBfnIP03ksXqlKePKq07hN3WXZjQb1Z8ln94WpICvRY6tAADawJXIbj6FnkPvTfueJQTHQHDRVpS85JVHkBwg88MILA58vFiWNA5xod7SoH98zJDXuCp6FeNr6fXskbzEDFB/0hbwBCkH8Gh2BIy/2QUSJHs8ategEbI18Sn4UuZ69mgGGdwiYifI04TKfgb+y3M6tQ3IFAl4f75osbCUP6KTfZvomMQCz3vk7QSSiGgTJa197uUgPbeExpp+MOu432JzdBfzloiyv4Z96MA2M2Qo4d9wkV/WK0M+nhMh5xBTKXlW6RgrLklQ3zQCRT1cT8qrOu2D/KSJhYt4ji+d/NwZljWJXDUPeg3366L65HfvuSc0EX9gGmxKSXzECFxOS/NXsGb7uk9mogCC5QH3JsoQXkngH+k7F3LUVlK5VOZot+zVrnwR4eFIoiroJhlQOeos9UxcZcEbovHztoivQMdg7gaSDWkV26/YoeU5AsxQeS6LIdy5o/pv49E8pTpaL7nuWFNp1EcpnPabTPDnVnhCZraqJQ57K2l1FJZ9CyDHs7PC/CmvevQajC6QGpY6j60J47jA4gLxcU41agONoPC1CJpvIvy3ABLp0Lz71cWh32GxvI1IqGydNm9BfxnNxFHLlzt6IfAN8wgna7eRVXgmzltryFXL6fgKsCaLP91tRRj//oBtuDfaMu5iLWW0SPjp+b7DmtFN3UiNRLhJmgXaF87rLbdhJLH0cwFwzT1c1ydoyV28HfMMYoolTQQHqjLmvfU7bSOsBZ2AfdHcxez4clhx4Qjkw2YVZcD5fl2dYEzhlOdiCL7WX7aOX3mQsLsBKaCe4hemlJcJJtuOzbCfvLXxm3apz/J9HdJxXvUzPcamwGmQDFaqSfS1w31GEhdhntWKzyXYcB2y9akeGEL7QbdqMs0Ka9H6ZNYSPkqpoE9J36GgQb6nAiNh4dnq4Du9Eg9qx8qg7Nsyy1UCR12xirrUxv4RJBWU/zRQTJhBEDvegJB1XLWg1AuuHe02z5Zg5NLm0LuvDq0W2RwyXmfi9mZs4JxpVx7Ec31uVCpX1rItBqZjvvpfxKEQLg9cY+PKeBIXIId5Gx18Y1jC+BqSYHW6e9h20xvRAWb+N58RDCeblDptHwZZ88TlGp1D8KwXRH+Xh5L1CSssGwbokt4DeQPzpmOp7gDB64zciusIPKDJFcVO4yFBaqQ7SSPQbNMDU5/1lvz3bOVmnGhwVNW0lpLwxDp2g9akOuLY6o+BKOdeFCpWzbJio3XOTT9lqgsna6ywUxA8kfFLDooiECxQg4cRlV+96FzQppHGfM9g/QwdP+7jHNnkjrGNzNh/rn0CVm3etIu3kHplb96kaHWupYW7xAfETScs1p1oFeMhwkSuvETbEKmu+nfIpukoKbJqtnSoRh983FDtzFH2sY6pjaAdDAPoIwxk93/CVgLTBISIxc8QNQmM3GRqQQL/jTw9riQzt6+z0+kq+ImcyQgPVBO05KQEl7GeoWFbfBPvryvgRIDWXqAShm5W59V+xpVocdI1Zh342yA4ARnlSmOj2clSFjRdR76z5TQnXm5+GqhjuxrDcp8C6FLEzNxZXZWH9JydNRC9ZmtLL0hLGoxQVwrne0FVeSeL2QNw+vhivcZMSyRpv7A2MRIX8CydwKnguTseDtQDiktvEEk8aNLNIYahMBaQL9Nw69EgTXQ2LU3DRpXmPyQfxi3djT+OW4PPsSgpnRRLQ0S3k0LsvkifI0dqJAi62VR3jfn9bXS14TjOaBQHRFGK2/HzeP8SsZZdxgD8b4VmfXLmWUgK106d501qYzGyL5A7rNVr1WrWGIaB7WUxJUUkl4B5K6vfhX+YohQ6e544AIe0FMzOtJTbf8kCSnoxh1Ym+O58GUADs6+s+ZBZUtrY/htJ0x0UUxcuzoloBFMQwmV4xK38Jm50D1riVtA6uc2JzxbzQ01khK+RWuUL/CJR9bWEPZOKsD+fCSEA+iZYmGu+PpzWyKRis4BwgZ9YBZtJkvAq2xHXFUWKPbnaE1gEgwOIszetqD0anXphi3lpOs9HcyhlVEkdNThXKAgrkMmWJBkIADAOuH0FmeTRmyORAh3HUbiqQSJLoKENsnzMEq+KnF6h4ORdg6pZDf4jBi57p0rLBhb4PdbmWdkko8Zqc4fyeVDrMx5txiFBAKLr7wTHi0FFyL0=,iv:e52JqEMsB1qWxkljnOs96e31y26mYrcdGti+TGkObP8=,tag:MVW4/Edkc1iOxhqV5pmZvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoeTB2dnVMK0ZkUkhXMzRT
            Yi95VVdRYzgxSWtSMnNRb014VDB1NndnUVRFCnhrZS95NXVFQW0vMmY2VHhIUE05
            b0VFc2xxa1JJckorUTBPejlud01iYVkKLS0tIFVSM0grajhrWU4zU0dIUHdpQkZt
            eVpFT1pHMFJPYTNtTlhtblFzZzJveEkK4ihkLkZFN35QcvigsTod1OWQc19Ozj2H
            95dh6IL4ROKug3HiLrcQwItsFiKP3+u+3RKx4mQN3CBSaM+ilvWLQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T12:21:24Z"
    mac: ENC[AES256_GCM,data:ycNc/XzZv4F1VKVmkWK3DSr7Wctu00TdIOzNtSKM6iz5612x7hQU1T9S79bB40AHkx1Brm36+x5PMPjM4JhF863dc+XqnQK56WPuVUESD+WNL72FZexNFh0zVEw/TF7CH6rlfITV70rQJpj2vkd6HtLhYJJvLP40Tj3rhDmrULo=,iv:mvmY08YpRhr17PZ2Y3pn5XJvCicu9G5GA2Sy3mjlf5s=,tag:YIDa2VaIhC2cM3QUlZR6Rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
