apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: canary
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: result[0] > 0.90
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.kube-prometheus-stack:9090
          query: >+
            sum(
              rate(nginx_ingress_controller_requests{canary="{{args.canary}}",status!~"[4-5].*"}[20s]))
              /
              sum(rate(nginx_ingress_controller_requests{canary="{{args.canary}}"}[20s])
            )
