apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: playground-sandbox
spec:
    secretTemplates:
        - name: playground-sandbox
          stringData:
            OTEL_EXPORTER_OTLP_TRACES_HEADERS: ENC[AES256_GCM,data:6h/y0YC7yv2G1Qi0DVK+rfkjYgFIHlprBsps3YYRV9OgiDbDdFOKAA==,iv:OiLFYeIgvmd9++z4o6QLI8vDQ37c1YPEWdO6R3HJ4+g=,tag:cXyKVXquUALgMF+nDYibzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS1VPL2ZObFoyUjhMai91
            QmsxNzJjRnc4K1RwWkYwVENMb3BrcUdMU1IwCllaSUU0QlN4V05SV2tuaEE0Skgy
            RFF3NDNVV0VnNkJMNExWQVdlOFYyVDAKLS0tIDZERDVINDVtQWJvUE5ydWtobGVJ
            YzJHeU51dHN0M3R5bU9MNkFCKzlDeVUKed9my6Bg2T1NuxMkUvi+s28BOZ/bbBLG
            1I1zghOkk7ZWhaY21LbAg8KlEjolCi1UyVY99XTLfdV9fL4byHVkTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T15:20:41Z"
    mac: ENC[AES256_GCM,data:bW6vyt576Wetu3TkrnU9N+grQX/bYBswIvTp9sA12QbJNEVKlzcRvv8DAySmC25LZVeAd1bvNl9hZCliUNMxUVgNKYR3Ylb9SX3UqRgr0e6JjOjy0KF9rJPCUYZOnDVw4II/ln3d/NOFd3cNb2Wv21qMiW06PbesCrZ2iNJUnJ8=,iv:uxAD+MEzLwjq7wDboNJi4DRtJnwKPGHYD4QXLgakbrw=,tag:ameNQVDWY38mAWnVYEtgtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
