configmap:
  # -- If enabled, promtail config will be created as a ConfigMap instead of a secret
  enabled: true

config:
  snippets:
    pipelineStages:
      - cri: {}
      - match:
          selector: '{app="kubernetes-event-exporter"}'
          stages:
            - json:
                expressions:
                  namespace: metadata.namespace
            - labels:
                targetNamespace: namespace
      - drop:
          source: "component"
          value: "runner"
      - labeldrop:
          - filename
  logLevel: warn

  clients:
    - url: http://loki.172.20.0.6.nip.io/loki/api/v1/push
      tenant_id: "my_org"
      basic_auth:
        username: admin
        password: ${LOKI_PASSWORD}

extraEnv:
  - name: LOKI_PASSWORD
    valueFrom:
      secretKeyRef:
        name: promtail-secret
        key: LOKI_PASSWORD
