configmap:
  # -- If enabled, promtail config will be created as a ConfigMap instead of a secret
  enabled: true

config:
  snippets:
    pipelineStages:
      - cri: {}
      - match:
          selector: '{app="kubernetes-event-exporter"}'
          stages:
            - json:
                expressions:
                  namespace: metadata.namespace
            - labels:
                targetNamespace: namespace
      - drop:
          source: "component"
          value: "runner"
  logLevel: warn

  clients:
    - url: http://collector.172.20.0.4.nip.io/insert/loki/api/v1/push?_stream_fields=container,cluster,app,component,namespace,node_name,job&ignore_fields=pod,filename
      tenant_id: "0:0"
      bearer_token: ${AUTH_TOKEN_LOGS}

extraEnv:
  - name: AUTH_TOKEN_LOGS
    valueFrom:
      secretKeyRef:
        name: promtail-secret
        key: AUTH_TOKEN_LOGS
