apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: admin-secret
spec:
    secretTemplates:
        - name: admin-secret
          stringData:
            ADMIN_ACCOUNT_PASSWORD_HASH: ENC[AES256_GCM,data:ylhRKgUNJ7Z6ulSkY8qvREw9PL8af1i+WracUe+4HYtKFe2KDd4dt4r4kEaFNyBxlipirWj2SoTJGNfo,iv:wlKtDM2AXq7Lto28GRPUp45W3owVzci6V9IBHf9+0eY=,tag:7XniR5+aJcxD+7sN+MhoNQ==,type:str]
            ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: ENC[AES256_GCM,data:J6f5TA3TptEUTPMM0F0MUQ52vQ==,iv:Vqa+1SjDXxWk7f5ua2tWBy3g7vln7KWs01JIcGMztWo=,tag:1eCOUNeUWE7795gZY7vKsw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVHhtRHhFakI0Tnh4VXl1
            c3kyYVRYNm02N2ZjSk53RXJXVEptdFJ5S0V3Cllsd0xmU2JMWVB4c1N1aFZocEJF
            K1FpZWp4ZXBJTXZ5ejZPZEo3SG5UK28KLS0tIDJEVE9QRGpnR0YzQW55RGpOUTQ0
            N1cvQ3pWdUZTSmtESDNPaWp6VC9zdGMKRBV8cqHccLAYMCLtIftiwjRCh2puzYE/
            yPjWXARpddUH+0xBYExZ+agi0FTBMi1ZNgi6M4gmQFiCudOwuwKX4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T20:41:19Z"
    mac: ENC[AES256_GCM,data:86Gwgwzeh995YuaOGC6Ubd2o2ZGL+H2k/wBCVdHP/ZDAwEHiO/FjZs/IjXYPZl1yGAZZRFdKYZ3TdBT5LZx65gQnLC41LKZO9eqOuIbaz3b788JXBhFywJAO9Sc7gnWvCIxdGvpM38Lh3eGk3leBRdKtkwycbC1j6gOhp7E9t30=,iv:IzEoJDJYJZN4Mfx6Y5dA34ru90KQhdYEsD5z1dPSbZY=,tag:JmHqgnh5OBC3QhWi08tzcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
