apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: trivy-operator
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchLabels:
            trivyOperator: "true"
        values:
          clusterName: "{{.name}}"
    - list:
        elements:
          - name: in-cluster
            values:
              clusterName: k3d-control
  template:
    metadata:
      name: "trivy-operator-{{.values.clusterName}}"
    spec:
      project: services
      source:
        chart: trivy-operator
        repoURL: https://aquasecurity.github.io/helm-charts/
        targetRevision: 0.25.0
        helm:
          valuesObject:
            trivy:
              severity: HIGH,CRITICAL
              ignoreUnfixed: true
            serviceMonitor:
              enabled: true
              labels:
                release: "prometheus-collector"
      destination:
        name: "{{.name}}"
        namespace: trivy-operator
      syncPolicy:
        # automated: {}
        syncOptions:
          - CreateNamespace=true
