apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps
  namespace: argocd
spec:
  project: apps
  source:
    path: apps/argo-apps
    repoURL: https://github.com/Utwo/k8s-playground
    targetRevision: HEAD
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated: {}
