apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchLabels:
            rollouts: "true"
        values:
          clusterName: "{{.name}}"
    - list:
        elements:
          - name: in-cluster
            values:
              clusterName: k3d-control
  template:
    metadata:
      name: "argo-rollouts-{{.values.clusterName}}"
    spec:
      project: infra
      sources:
        - repoURL: https://github.com/Utwo/k8s-playground
          path: infra/argo-rollouts
          targetRevision: HEAD
          ref: myRepo # repo is available via symlink "myRepo"
          directory:
            recurse: true
        - chart: argo-rollouts
          helm:
            valueFiles:
              - $myRepo/infra/argo-rollouts/values.yaml
          repoURL: https://argoproj.github.io/argo-helm
          targetRevision: 2.40.5
      destination:
        namespace: argo-rollouts
        name: "{{.name}}"
      syncPolicy:
        # automated: {}
        syncOptions:
          - CreateNamespace=true
