apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            certManager: "true"
    - list:
        elements:
          - name: in-cluster
  template:
    metadata:
      name: "cert-manager-{{name}}"
    spec:
      project: infra
      sources:
        - chart: cert-manager
          helm:
            valuesObject:
              global:
                leaderElection:
                  namespace: cert-manager
              crds:
                enabled: true
              prometheus:
                enabled: false
          repoURL: https://charts.jetstack.io
          targetRevision: v1.19.2
      destination:
        namespace: cert-manager
        name: "{{name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
