apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: infra
  sources:
    - chart: cert-manager
      helm:
        valuesObject:
          global:
            leaderElection:
              namespace: cert-manager
          crds:
            enabled: true
          prometheus:
            enabled: false
      repoURL: https://charts.jetstack.io
      targetRevision: v1.16.1
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
