apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchLabels:
            ingressNginx: "true"
        values:
          clusterName: "{{.name}}"
    - list:
        elements:
          - name: in-cluster
            values:
              clusterName: k3d-control
  template:
    metadata:
      name: "ingress-nginx-{{.values.clusterName}}"
    spec:
      project: infra
      source:
        chart: ingress-nginx
        helm:
          valuesObject:
            controller:
              metrics:
                enabled: true
                serviceMonitor:
                  additionalLabels:
                    release: "kube-prometheus-stack-{{.values.clusterName}}"
                  enabled: true
              # -- Will add custom configuration options to Nginx https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/
              config:
                client-body-buffer-size: 1000M
                proxy-body-size: "50m"
                proxy-read-timeout: 3600
                proxy-send-timeout: 3600
                proxy-real-ip-cidr: "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20,197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
                use-forwarded-headers: "true"
                enable-real-ip: "true"
                use-gzip: "true"
                disable-access-log: "true"
                enable-brotli: "true"
        repoURL: https://kubernetes.github.io/ingress-nginx
        targetRevision: 4.12.0
      destination:
        namespace: ingress-nginx
        name: "{{.name}}"
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
