---
# Source: playground-sandbox/templates/backend/metric-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-metrics
  labels:
    helm.sh/chart: playground-sandbox-0.1.0
    app.kubernetes.io/name: playground-sandbox
    app.kubernetes.io/instance: playground-sandbox
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    app: backend
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9464
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/name: playground-sandbox
    app.kubernetes.io/instance: playground-sandbox
    app: backend
