---
# Source: playground-sandbox/templates/backend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    helm.sh/chart: playground-sandbox-0.1.0
    app.kubernetes.io/name: playground-sandbox
    app.kubernetes.io/instance: playground-sandbox-dev
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
    app: backend
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: playground-sandbox
    app.kubernetes.io/instance: playground-sandbox-dev
    app: backend
