---
# Source: playground-sandbox/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modify-pods
  namespace: public-staging
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
