apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-notifications-secret
spec:
    secretTemplates:
        - name: argocd-notifications-secret
          annotations:
            sopssecret/managed: "true"
          labels:
            app.kubernetes.io/component: notifications-controller
            app.kubernetes.io/instance: argocd
            app.kubernetes.io/name: argocd-notifications-controller
            app.kubernetes.io/part-of: argocd
          stringData:
            githubAppPrivateKey: ENC[AES256_GCM,data:6Suk8kD8R5kv+hQmVzAwbSod3nHJHlwd7GHUwmPVWL9I9OMhGyVwhAbxtPcNNfU7ICLEZ4mrvM+LWCGjc9HKg+G71G9AV6HhaYa6D/S7Etp/kco6mSvJflr0HAg+XHOXOQ2U4yosYnkiOL2Krl9iHvxRyeBP4Ar+Xdilp/fxCXAzHj39J9jUanl4IuowLIFyQAFtDv8jrmEMF3ar1n7PkKHx6ogQNSZNFTuuN25f5YytImm8c4gdWysi/DrwQbT56SeveQanA5tsQHedTzgz7t6xtlYYAYftY/4Wv5IjCe+RcQPphmBXez/2OhBQtpq1jdQ4HIc/dCQF10eWyFOQBUz9v0lacJMD43Gc7I/Lu09vJ2W51wVgAiumTOTnqU8x4Om3QcH6ocUzlIJvr5PNMrxcsmy/otH5mcuKLjjRQ1fTGfxP3BwIx/hNOCDmeeVPgmxZzhHQVAJe3cx7T13yvR1BJaacUCP80Zc0r55sR24co/EPRaw4t+VIdQR1Bw9vsQaxoHSzLxuQEjJtwKr21CcBWQ/3oe1QAQ8j9VIaYRmugdTg/hZnlJkQa9mFaGWIe7lAonzz0OxfajrorYFIx4Cy2YqeuscEHzLVqTR7ZLOF23KXZmt0XxX7NABCPDasc06p/HBJO4M3gscfYKl7mFg9uFn0pgzYKab0qDJGoghZ4xMmMzc/3BLbsoVd4WlUHhIgllyAGsIPksdz+wb41H217b/IwM+TcvBFiIJpr1Y6n4oCO9JOneF1onUEl0vAUO6aIPez+bsOaO2K77h7ijyRO0W28b2G7JwEJqUzqjWbfb+wBRxFikfg/kpfb8ymKYn1s+B2eEfcgVv/Wl/X8/t6/BPDrjtw/M3PJsuzNgertjet4YLlhaVV2MoOsa4y2hbzBDnnNkP0af9mvZ9NPaSK2Dgn5M4cotsfAFeO1W94DxCRqMjepXSUpg+KFgm77ihRHAzq1l1mTb23ikjz5DNBijQwzltbDP4k0JXKEZJNBBss6NVyNSNpIy8TDbSPxtfzlOOn6zJdXfHiYy6SWqflk+EgpNH48/5iI6VPgYyf5Am3QlIF1GcZdH0r5Ghz6xXmyH3Mu3zylFvHWiwryNfrPy6BxPFqCQpzyEducmQQNaUsnyEQipUeJwsHc7cJ8Yfkh7VJfT5LSF0mqHLm7pqJ/mILAjhCachOxnMcxlcGm35Ndl6ioVl1GKxnAFkl2fhlYJvzUe+hZb45ezIUx3WRLX5z1G9mvsNuBYnSvIejKXsvRpzyfK7dxGa74EO1vzHyAcdekatLkT/A6N70/I7N48cf3ogXcp0MUJv9kDo8t65whFzD7f3IFldd356LEwH02QuWDXvakXJ7SM0UpQi0F3XSW3FYj1YUF3Gjy8/Juk3cpgd7sFOx9IACu4n9N3WPo9Z6219KzioPXlj3FIU7iz8hzb8BrUTKAuZhQYheNCVtkdXGHOBXGDLoWaJZbz9p6lPRwdT64gsZj+Q5Ay8N55cjt+EoczVuFzuwh8wOqBv7rX/E4zZucbe4szyVg/Kzh1I8scH+JFiY8i9lnjc4FgPr0qWfEDdQcFyMwhfn0JGncaem/exmE4obnIVQi9qFs+EIQ2lrt3DoPrzBjvGhVNciL3Q50TimXFL98IrdyBe87tdlTXvQwToa3PGcqNB+xXTPY3RtNM4B/Qe9pq9aDIIA+S0bgWDSLRBA2GumWM7ncbcQyQeEp8yITLUxV43kFgcqxJFN08NgKAIEcLujmmNlOC3M4WFn9vj4R9FKVG+MyLZparFIlUIURqLk2ygkhN3H7N8GvCe9yMyHGxMToMcXPA6USY9ruN8w/IbdLUb3xrYgXggdCvLMuqfQ7Ros8MrX2XBQkDYVa7pvdP1sukVY4NOpPMHIhz/cKPVWwpNfKgzz7KQ/9KJxHku4liKkNEHicvqddpfYBS7nEdekRpSOOEtL5iuwt6VW6ShqWgEw9NRp2KosqdkivVSEzVRt38M40H8akYxcW+KRezOwJZqCXH8x94UQOh3AcYWC0K03+Xa16kprHBd5S73p17S8ZOnF9AAaSbOQIfXViYGHNEaa/BS46TPX4Bt0UAtCtKjNVSn84AiqnA/HmepwcmvUP/2YB673LB5u0oxlSgPm7BoF9nQXHnYWjHlyqvHhCPUw+D7NiTo/zhVefahxbTTK1hLWYSM72pP0oRLMD1iHujVizixb7IPi5Yh4qE6RLqZ6q1uDsYlvMNrrSeA=,iv:/KbDCVu9CqAmrBkRj+UOVlfUrszyrhJXaFb/eR0sOwQ=,tag:vwIijbqXDGVr3H+qegg4iQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4WE5uZUNHRDdWbUF6MTYy
            MlMxSnF6Tzd5Z3VGL1pmTHJOaDE4NHZieTJBCnJjcmhuaWhndmRtL1ZBSG96RlBZ
            NU1lS3kvQ05yRnd4OENZOGtJbDhQencKLS0tIGFpMHpOaHVldzlxTWh4eHlsd0cw
            S3FNRWJ4VGNhcGJPTUpSM2gyTXNMR2sKpDx0z35tnC7kLJSZNIYzfPh/oXpsf0ki
            D85o+qxeQhx2yNkCkpu0PSpiaxU9zJsCUNFpEIMEXGkIFjbQOyXoVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-20T09:38:11Z"
    mac: ENC[AES256_GCM,data:XxQl/vHMKVfWNU87HEdeVbfWx3tonZ+WSwzp19Rt1vYj1DlnJT1umSAElTHnwvKGJGH0unh3CKEgtI7TOpPzgXO1Y/oTauLiREnd2lO0pZSICMKOygKp+9HG95CvVcwAhkGRmqmOI8KhaupBfFxRXzoq6KyDYoe+tQY27Y/vaxA=,iv:IDd3t1kBgUzXB47BFeHUmfk/9IVrFZmrjw+AeHvcosg=,tag:dPS0XrI/6XtATtma7Kfjgg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
