apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argocd-secret
spec:
  secretTemplates:
    - name: argocd-secret
      labels:
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      stringData:
        admin.password: ENC[AES256_GCM,data:R23H+gcgE695FhdTdECrbhhPy3d3yVw2Idrf7zJ3QQ0Wf5fAu0GNyhr96h58OjMOUveYeZFuh3AXJZ00,iv:spLASA+IfsX95w5rVgy+O5cG02dbUKHjJ5d+dayo7ps=,tag:aDw+HnZ1azd+ZO1Q5KuSLg==,type:str]
        admin.passwordMtime: ENC[AES256_GCM,data:cS7VvqcP8HqPs+EnkJNapOoB/aY=,iv:CA6zkSlEJbxLrlkcbY+IYwVIK1T4ewJ25Zlgv2JzSm4=,tag:9FfNu/pfYSh8tScrg+0aCQ==,type:str]
        server.secretkey: ENC[AES256_GCM,data:x0ruD5+HluYrQmUF03oWTTV80IqJxJerMHADLrIpXSfi6+SL6Sy7Ns8ILdQ=,iv:TmhKfuFP49y9Ojrd3oXE6W6lHoAw5gW7nuUMYUP9gKM=,tag:67niZ56p7+GUJLcNtVSmcQ==,type:str]
        dex.github.clientSecret: ENC[AES256_GCM,data:2GhLPMAlSDIvmk+vmh/q0mJVoTGe28CdyiLLoxy7m/QsQviOJn04hQ==,iv:p45BZcwgM1VFNpcb/VWaro0YD9p6IIJryawVP4/u6bQ=,tag:+IKay9lNg6tNTOAdtuVV9A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZEo5cjFsT0FzdGNqUC84
        VTk5L0M1aEF4SEFhM0pxZnJDWkJjVXJiRFJzClJZclN3R3VwRTlEUjJvTEZLQldq
        cy9TNzB2RTJFeWJWRjZUczFZZmJicm8KLS0tIEFEZ0lTRzVSOEE1KzFMaFoyYzRZ
        RGRYSzlnbWpBQkVJS1hJTFllZjU5eUEKBROXDWdlynF6f7uFrbiukczdXxS0bHvU
        wriewxcIpLZMRibZGUQAYW0ZmBWSdwBeyckIgUR+7/rSN1sA3C5eAA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-13T19:07:32Z"
  mac: ENC[AES256_GCM,data:jvT6oPJ6QsR/Xm1YXHAPnExNusWIhcaIWbhzZoGgrZiyq39aF9hNJkIRBDRYH72mAmiElKg8qE4aZZUY5H88+5BFh7wnmg42Zzfdq4KUUb02yrkFXoWIj5/t8yETcS1VzrOjQmgARH1Rf+DlbMm7gPRtUmjJCIUcUOaaqs04LP0=,iv:49SS6Wz85RH2diJi1PXBRBG/nxqPJa15EU1wvhhEx3Y=,tag:jHwYoUzobLCIe/DCZeL9Nw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.3
