apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-secret
spec:
    secretTemplates:
        - name: argocd-secret
          labels:
            app.kubernetes.io/instance: argocd
            app.kubernetes.io/name: argocd-secret
            app.kubernetes.io/part-of: argocd
          annotations:
            sopssecret/managed: "true"
          stringData:
            admin.password: ENC[AES256_GCM,data:R23H+gcgE695FhdTdECrbhhPy3d3yVw2Idrf7zJ3QQ0Wf5fAu0GNyhr96h58OjMOUveYeZFuh3AXJZ00,iv:spLASA+IfsX95w5rVgy+O5cG02dbUKHjJ5d+dayo7ps=,tag:aDw+HnZ1azd+ZO1Q5KuSLg==,type:str]
            admin.passwordMtime: ENC[AES256_GCM,data:cS7VvqcP8HqPs+EnkJNapOoB/aY=,iv:CA6zkSlEJbxLrlkcbY+IYwVIK1T4ewJ25Zlgv2JzSm4=,tag:9FfNu/pfYSh8tScrg+0aCQ==,type:str]
            server.secretkey: ENC[AES256_GCM,data:x0ruD5+HluYrQmUF03oWTTV80IqJxJerMHADLrIpXSfi6+SL6Sy7Ns8ILdQ=,iv:TmhKfuFP49y9Ojrd3oXE6W6lHoAw5gW7nuUMYUP9gKM=,tag:67niZ56p7+GUJLcNtVSmcQ==,type:str]
            dex.github.clientSecret: ENC[AES256_GCM,data:2GhLPMAlSDIvmk+vmh/q0mJVoTGe28CdyiLLoxy7m/QsQviOJn04hQ==,iv:p45BZcwgM1VFNpcb/VWaro0YD9p6IIJryawVP4/u6bQ=,tag:+IKay9lNg6tNTOAdtuVV9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZEo5cjFsT0FzdGNqUC84
            VTk5L0M1aEF4SEFhM0pxZnJDWkJjVXJiRFJzClJZclN3R3VwRTlEUjJvTEZLQldq
            cy9TNzB2RTJFeWJWRjZUczFZZmJicm8KLS0tIEFEZ0lTRzVSOEE1KzFMaFoyYzRZ
            RGRYSzlnbWpBQkVJS1hJTFllZjU5eUEKBROXDWdlynF6f7uFrbiukczdXxS0bHvU
            wriewxcIpLZMRibZGUQAYW0ZmBWSdwBeyckIgUR+7/rSN1sA3C5eAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-14T12:05:42Z"
    mac: ENC[AES256_GCM,data:FJvoy3gEG63Fig+s8R/R/Pj9SA7LyUOPDFhXVU/P52J3upxau3QsonFmblsSPBLw4g5bu9oLQnR1GAS5qhhfaW0/tnzOZgC5WEx+yq6QEls8+2E4CR8DFJ5LZqLGxC8dsWWdfrzFCbCJwiO/J2l5zVgRg3ftL0xJF3yieO16T4U=,iv:dAh2VpcNt6+Ym0J3wLQtrvu2YZoiz5tqa25k7ng/asw=,tag:fimxP3/D6xow5XZf20U1+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.3
