apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: argocd-secret
spec:
  secretTemplates:
    - name: argocd-secret
      labels:
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      stringData:
        admin.password: ENC[AES256_GCM,data:ys6Kc2Zn75nncBu35HPCVKkTDcaaR/yBBVbGTTnk3DoE5i9YBenbjkTiTRJJ+KllXUSGuGOY1NDqAK28,iv:RU03j47kWd6rUVGXVJk2ZwmSHUAj8wHpex1nzun9V7c=,tag:sLSQA2U8noUZgCUZB8+Q9Q==,type:str]
        admin.passwordMtime: ENC[AES256_GCM,data:OD0jupt6cBepf5edbPpNNEXvS8c=,iv:z4Gg8wW2WxeXQDEIfvosC94V9Cdet+EatpH2tDFs/60=,tag:yWAQBQAmKIXLSzfmXU3dyQ==,type:str]
        server.secretkey: ENC[AES256_GCM,data:vqAR+XiMiWQ8wtwxgLD1l11yHz8f/AEi8hXWW8IzFcFT1JBdpWDc+n4sxRI=,iv:qPBvMIfCmsjYpuO/G07OLeNXPfozjitdiGilPnQ7vEo=,tag:hCsITX1zd7xUFxYUHKnSrQ==,type:str]
        dex.github.clientSecret: ENC[AES256_GCM,data:hkOXL53oOD5KasOILrso9SKOVhVR5jSuwF5UlLcqUOeV6SycvZrBGg==,iv:vosuqHNRGStQHIOyI3G19POd14+nHqPstE9vY8ROcW0=,tag:VKxuXCLqwAMuGnYl3iRuxA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1g7mudl58ufepz8nf5hyksnnhzkursvwumlvm5xc9td0uqlq2j4ys6y9rpm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4MFBmV0VubHc3a1M2SzYx
        RDl2TjJUQTFlNzdlYTd2bVlRMGpyNWtZZTJFCnJCMjFFOC92UTlZOFQvUmRlSm9u
        ZXdVNnlIWlhqY3NKOGw1OGEyc0FFbGcKLS0tIHA0YWdPMFVxd1AxbHFJNVFKUVFT
        WnphTjJzczdRS1pqTEJiSVhES2RoYkkKJU4enDWvtAe+WmNlUTaJbDn/NiD0wYso
        /AL/OixStI9e+ZDQXbMxOWt03ZeVOL9D8j+0u2Gj2sS9hzjokJKj/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-13T18:40:14Z"
  mac: ENC[AES256_GCM,data:+uGen9OsF5+HGVlbSc5h7Pe+DPynSejvL/PnaRQHjm7rQEOnAeV6y++qL8VcfuEs9eUVfabxV7f7bTVPOzARIMvgNb+Dw4MrDwueTKyFgoFtRpd0tO4Nq4uqZEvtmSeWbkmaDvqZ1aS3zYzm/AW+KmHRHGQswJyCYd9ANTwQeWM=,iv:WWJnhqHHiXNkAQrvYs4qqARAQz/HEorAl4fKRLwTBO0=,tag:Blqjvf/VE+TU8te5V5sRaA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
