apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml?ref=v2.13.3
  - namespace.yaml
  - project.yaml
  - ingress.yaml
  # - repo-secret.yaml

patches:
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-cm.yaml
