apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml?ref=v2.13.3
  - namespace.yaml
  - project.yaml
  - ingress.yaml
  - argocd-secrets.yaml
  - repo-secrets.yaml
  - argocd-notifications-secret.yaml
  - clusters/k3d-apps-secret.yaml
  # metrics
  - metrics/argocd-metrics.yaml
  - metrics/argocd-repo-server-metrics.yaml
  - metrics/argocd-server-metrics.yaml
  - metrics/grafana-dashboard.yaml

patches:
  - path: argocd-cmd-params-cm.yaml
  - path: argocd-cm.yaml
  - path: argocd-rbac-cm.yaml
  - path: argocd-notifications-cm.yaml
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
        annotations:
          "sopssecret/managed": "true"
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-notifications-secret
        annotations:
          "sopssecret/managed": "true"
