apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Kubernetes Infrastructure Applications
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Monitoring related applications
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: Applications
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - "*"
