# we do not actually apply this file. It is just an example of how to register private registries in ArgoCD
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: github-k8s-playground-repo
spec:
  secretTemplates:
    - name: github-k8s-playground-repo
      labels:
        argocd.argoproj.io/secret-type: repository
      stringData:
        type: ENC[AES256_GCM,data:COH+,iv:QEwEWwncEngNLciwhUtkZUwKvXvXR0NA2eFKd1vbess=,tag:H25rLk6bmqvIy2j2+q5RQA==,type:str]
        url: ENC[AES256_GCM,data:1qbGbcpzTFgjjxf0bvFrt5Ee/BMfKz1JjO7e8JwUL6Ww+rqLfA==,iv:EaSVYFRx0AFNwlr9EOhz5qONVAmghmkG38wGKO51KpM=,tag:yb1h5ZNglgYjlHk6+JkCmw==,type:str]
        password: ENC[AES256_GCM,data:b0aywqUXuJzPk7oXjMW5Cw9UXQo6anUVK+cX7SCtmrLFnOnxfoqp19ufV53y8h459HS2aI8ipDwev0KIo7YchnzjWoEldBNZQpxxEK16Dndl5V8KYVE9syQOvvVt,iv:dOzMBN2fhJzqYacZeq7miFQDRVoYHje+5PljbDI4Hjk=,tag:ZnehhzBv1eMDG+YjQyeqHA==,type:str]
        username: ENC[AES256_GCM,data:EuTx0g==,iv:KkTT986HEdFK/7p6+E/Ec4P/A+FpbOib3RxiUdi1cLQ=,tag:ixeop1f818fovYDHBpvjTQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1gsvhj42uxwcp5hjzy74wqm2we3cfyycje6y4hnc8evtlqnypq3wqkwpss9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQjVrbmRHUlhxTlF5MDhP
        MWlPZjhlMHJ0bHY1OWg2bm5FK0pGMU5wTjFnClMxZlU4UG5mRGdHMkdJZFRuMEFY
        ZTlyeFhYVG9tSHNYUU1zZmpmTjRnV1UKLS0tIE5oZlhLVGZUL2JJamVxdXFJa2Ur
        aUplOUdsQzVTdkt3Vm5RaHR6bmt2cDAKUjJVq0bMklRHYRi71yipbB+aT2sysDES
        5XKeba3b+4u/bpn84GWiTvuRKZNUEDptuLaHaJfhbX2A50fX0N8LlA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-02T10:27:49Z"
  mac: ENC[AES256_GCM,data:OmjyJ+PKcLm3ocyTBxbXYnm9YSqERWGHIern66oYihTs/lJvw4Fd84iwgnPBqusgC4RrXk4y9n6eaCQyLww8B4j3w1Jp7pR1DxZJVDKC4g/WEnRivWUS67fFeOUkYuoAkCMNk0wlUDb4VAavvgZX7bvu3t67NJBbfxs9X6YlL60=,iv:ItxJMCKW6RNVyY+O9sHUcpQrgoCN3cTKJ3Xf5N2yOJk=,tag:UCVRRXkPT6wv1Z5jC6O9ow==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
