destinations:
  - name: prometheus
    type: prometheus
    url: http://collector.k3d-sandbox-control-serverlb.orb.local/api/v1/write
    auth:
      type: bearerToken
      bearerTokenKey: PROMETHEUS_AUTH_TOKEN
    secret:
      create: false
      name: alloy-secret
      namespace: alloy
  - name: loki
    type: loki
    url: http://loki.k3d-sandbox-control-serverlb.orb.local/loki/api/v1/push
    tenantIdKey: TENANT_ID
    auth:
      type: basic
      usernameKey: LOKI_USERNAME
      passwordKey: LOKI_PASSWORD
    secret:
      create: false
      name: alloy-secret
      namespace: alloy
  - name: tempo
    type: otlp
    url: http://tempo.k3d-sandbox-control-serverlb.orb.local/otlp
    tenantIdKey: TENANT_ID
    metrics:
      enabled: false
    logs:
      enabled: false
    auth:
      type: basic
      username: "admin"
      passwordFrom:
        secretKeyRef:
          name: alloy-secret
          key: TEMPO_PASSWORD
    secret:
      create: false
      name: alloy-secret
      namespace: alloy

clusterEvents:
  enabled: true

clusterMetrics:
  enabled: true
  kubelet:
    jobLabel: kubelet
  cadvisor:
    jobLabel: kubelet
  node-exporter:
    jobLabel: node-exporter
    metricsTuning:
      includeMetrics:
        - node_uname_info
        - node_disk_io_time_seconds_total
        - node_disk_io_time_weighted_seconds_total
        - node_load1
        - node_vmstat_pgmajfault
  kube-state-metrics:
    jobLabel: kube-state-metrics
  windows-exporter:
    deploy: false
    enabled: false

applicationObservability:
  enabled: true
  receivers:
    otlp:
      grpc:
        enabled: true

# autoInstrumentation:
#   enabled: true

prometheusOperatorObjects:
  enabled: true
  crds:
    deploy: true

podLogs:
  enabled: true

alloy-metrics:
  enabled: true

alloy-logs:
  enabled: true

alloy-receiver:
  enabled: true
  alloy:
    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP

alloy-singleton:
  enabled: true

integrations:
  collector: alloy-singleton
